# Name: 00_setup.R
# Description: Setup script - package loading, path configuration, read_sdtm helper
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

# ---- Packages ----
library(admiral)
library(dplyr)
library(tidyr)
library(lubridate)
library(stringr)
library(haven)
library(datasetjson)

# ---- Paths ----
WORKSPACE <- "/private/var/folders/k_/kns3xnh95lsc57yvx3rhxj100000gn/T/mediforce-local-workspace-hB8wZb"
SDTM_DIR  <- file.path(WORKSPACE, "data", "sdtm")
ADAM_DIR  <- file.path(WORKSPACE, "data", "adam")

dir.create(ADAM_DIR, showWarnings = FALSE, recursive = TRUE)

# ---- Helper: read SDTM domain ----
read_sdtm <- function(domain, sdtm_dir = SDTM_DIR) {
  json_path <- file.path(sdtm_dir, paste0(tolower(domain), ".json"))
  xpt_path  <- file.path(sdtm_dir, paste0(tolower(domain), ".xpt"))
  sas_path  <- file.path(sdtm_dir, paste0(tolower(domain), ".sas7bdat"))
  if (file.exists(json_path)) {
    datasetjson::read_dataset_json(json_path)
  } else if (file.exists(xpt_path)) {
    haven::read_xpt(xpt_path)
  } else if (file.exists(sas_path)) {
    haven::read_sas(sas_path)
  } else {
    stop(paste("SDTM domain", domain, "not found in", sdtm_dir))
  }
}

# ---- Helper: export ADaM dataset ----
write_adam <- function(dataset, name, adam_dir = ADAM_DIR) {
  # Export as XPT (SAS transport)
  xpt_path  <- file.path(adam_dir, paste0(toupper(name), ".xpt"))
  haven::write_xpt(dataset, xpt_path)
  cat("Exported", name, "->", xpt_path, "\n")
  cat("  Records:", nrow(dataset), "\n")

  # Also save as Dataset-JSON
  json_path <- file.path(adam_dir, paste0(tolower(name), ".json"))
  tryCatch({
    # Build minimal column metadata from data frame
    col_types <- sapply(dataset, function(x) {
      if (is.numeric(x)) "float" else "string"
    })
    items <- data.frame(
      variable = names(dataset),
      data_type = col_types,
      stringsAsFactors = FALSE
    )
    ds_json <- datasetjson::dataset_json(
      dataset,
      item_oid = paste0("IG.", toupper(name)),
      name = toupper(name),
      dataset_label = paste("ADaM", toupper(name), "dataset"),
      columns = items
    )
    datasetjson::write_dataset_json(ds_json, json_path)
    cat("  Also exported as JSON ->", json_path, "\n")
  }, error = function(e) {
    cat("  JSON export skipped:", conditionMessage(e), "\n")
    # Fallback: write as plain JSON via jsonlite if available
    if (requireNamespace("jsonlite", quietly = TRUE)) {
      jsonlite::write_json(dataset, json_path, na = "null", auto_unbox = TRUE)
      cat("  Fallback JSON written via jsonlite ->", json_path, "\n")
    }
  })

  invisible(dataset)
}
