# Name: 01_adsl.R
# Description: Generate ADSL dataset for CDISCPILOT01
# Source SDTM: DM, DS, EX, SV, VS, QS, SC, SUPPDM, SUPPDS
# Supports TLGs: T-14.1.1, T-14.1.2, L-16.1.1, L-16.2.1
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

# ---- Setup ----
library(admiral)
library(dplyr)
library(lubridate)
library(stringr)
library(tidyr)

# Source helper functions
source("/workspace/code/00_setup.R")

# ---- Read source data ----
cat("Reading SDTM data...\n")
dm <- read_sdtm("DM")
ds <- read_sdtm("DS")
ex <- read_sdtm("EX")
sv <- read_sdtm("SV")
vs <- read_sdtm("VS")
qs <- read_sdtm("QS")
sc <- read_sdtm("SC")
suppdm <- read_supp("DM")
suppds <- read_supp("DS")

# ---- Basic ADSL structure from DM ----
cat("Creating basic ADSL structure...\n")
adsl <- dm %>%
  select(
    STUDYID, DOMAIN, USUBJID, SUBJID, SITEID,
    AGE, AGEU, SEX, RACE, ETHNIC, ARM, ARMCD,
    RFSTDTC, RFENDTC, RFXSTDTC, RFXENDTC,
    DTHDTC, DTHFL
  ) %>%
  mutate(
    TRT01P = ARM,
    TRT01PN = case_when(
      ARMCD == "PBO" ~ 1,
      ARMCD == "XAN-LOW" ~ 2,
      ARMCD == "XAN-HIGH" ~ 3,
      TRUE ~ NA_real_
    ),
    TRT01A = ARM,
    TRT01AN = TRT01PN
  )

# ---- Derive population flags ----
cat("Deriving population flags...\n")

# Safety population (received at least one dose)
safety_subjs <- ex %>%
  filter(!is.na(EXSEQ)) %>%
  distinct(USUBJID) %>%
  mutate(SAFFL = "Y")

# Intent-to-treat population (all randomized)
itt_subjs <- dm %>%
  filter(!is.na(RFSTDTC)) %>%
  distinct(USUBJID) %>%
  mutate(ITTFL = "Y")

# Efficacy population (has post-baseline ADAS-Cog and CIBIC+ assessments)
efficacy_subjs <- qs %>%
  filter(
    QSTESTCD %in% c("ADAS11", "CIBIC+"),
    VISITNUM > 3,  # Post-baseline
    !is.na(QSSTRESN)
  ) %>%
  group_by(USUBJID, QSTESTCD) %>%
  summarise(has_postbaseline = n() > 0, .groups = "drop") %>%
  group_by(USUBJID) %>%
  summarise(
    has_adas = any(QSTESTCD == "ADAS11" & has_postbaseline),
    has_cibic = any(QSTESTCD == "CIBIC+" & has_postbaseline),
    .groups = "drop"
  ) %>%
  filter(has_adas & has_cibic) %>%
  mutate(EFFFL = "Y") %>%
  select(USUBJID, EFFFL)

# Study completion flags
completion_flags <- ds %>%
  filter(DSCAT == "DISPOSITION EVENT") %>%
  group_by(USUBJID) %>%
  arrange(DSSTDY) %>%
  slice_tail(n = 1) %>%
  ungroup() %>%
  mutate(
    COMPLFL = ifelse(DSDECOD == "COMPLETED", "Y", NA_character_),
    DISCONFL = ifelse(!DSDECOD %in% c("COMPLETED", "SCREEN FAILURE"), "Y", NA_character_),
    DISCONREA = ifelse(DISCONFL == "Y", DSDECOD, NA_character_)
  ) %>%
  select(USUBJID, COMPLFL, DISCONFL, DISCONREA)

# Merge population flags
adsl <- adsl %>%
  left_join(safety_subjs, by = "USUBJID") %>%
  left_join(itt_subjs, by = "USUBJID") %>%
  left_join(efficacy_subjs, by = "USUBJID") %>%
  left_join(completion_flags, by = "USUBJID") %>%
  mutate(
    SAFFL = ifelse(is.na(SAFFL), "N", SAFFL),
    ITTFL = ifelse(is.na(ITTFL), "N", ITTFL),
    EFFFL = ifelse(is.na(EFFFL), "N", EFFFL),
    COMPLFL = ifelse(is.na(COMPLFL), "N", COMPLFL),
    DISCONFL = ifelse(is.na(DISCONFL), "N", DISCONFL)
  )

# ---- Derive baseline characteristics ----
cat("Deriving baseline characteristics...\n")

# Baseline weight (from VS at baseline visit)
weight_bl <- vs %>%
  filter(
    VSTESTCD == "WEIGHT",
    VISIT == "BASELINE",
    !is.na(VSSTRESN)
  ) %>%
  group_by(USUBJID) %>%
  arrange(VSDTC) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  select(USUBJID, WEIGHTBL = VSSTRESN)

# Baseline height (from VS at screening)
height_bl <- vs %>%
  filter(
    VSTESTCD == "HEIGHT",
    VISIT == "SCREENING",
    !is.na(VSSTRESN)
  ) %>%
  group_by(USUBJID) %>%
  arrange(VSDTC) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  select(USUBJID, HEIGHTBL = VSSTRESN)

# Baseline BMI
bmi_bl <- weight_bl %>%
  inner_join(height_bl, by = "USUBJID") %>%
  mutate(
    HEIGHT_M = HEIGHTBL / 100,
    BMIBL = WEIGHTBL / (HEIGHT_M * HEIGHT_M)
  ) %>%
  select(USUBJID, WEIGHTBL, HEIGHTBL, BMIBL)

# Baseline MMSE
mmse_bl <- qs %>%
  filter(
    QSTESTCD == "MMSE",
    VISITNUM == 3,  # Baseline visit
    !is.na(QSSTRESN)
  ) %>%
  group_by(USUBJID) %>%
  arrange(QSDTC) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  select(USUBJID, MMSEBL = QSSTRESN)

# Baseline ADAS-Cog
adas_bl <- qs %>%
  filter(
    QSTESTCD == "ADAS11",
    VISITNUM == 3,
    !is.na(QSSTRESN)
  ) %>%
  group_by(USUBJID) %>%
  arrange(QSDTC) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  select(USUBJID, ADASCOGBL = QSSTRESN)

# Baseline CIBIC+
cibic_bl <- qs %>%
  filter(
    QSTESTCD == "CIBIC+",
    VISITNUM == 3,
    !is.na(QSSTRESN)
  ) %>%
  group_by(USUBJID) %>%
  arrange(QSDTC) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  select(USUBJID, CIBICBL = QSSTRESN)

# Disease duration at baseline
disdur_bl <- sc %>%
  filter(
    SCTESTCD == "DISDUR",
    !is.na(SCSTRESN)
  ) %>%
  group_by(USUBJID) %>%
  arrange(SCDTC) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  select(USUBJID, DISDURBL = SCSTRESN)

# Age groups
adsl <- adsl %>%
  mutate(
    AGEGR1 = ifelse(AGE < 65, "<65 years", ">=65 years"),
    AGEGR1N = ifelse(AGE < 65, 1, 2)
  )

# Merge all baseline characteristics
adsl <- adsl %>%
  left_join(bmi_bl, by = "USUBJID") %>%
  left_join(mmse_bl, by = "USUBJID") %>%
  left_join(adas_bl, by = "USUBJID") %>%
  left_join(cibic_bl, by = "USUBJID") %>%
  left_join(disdur_bl, by = "USUBJID")

# ---- Add labels ----
cat("Adding variable labels...\n")
attr(adsl$USUBJID, "label") <- "Unique Subject Identifier"
attr(adsl$SUBJID, "label") <- "Subject Identifier for the Study"
attr(adsl$SITEID, "label") <- "Study Site Identifier"
attr(adsl$AGE, "label") <- "Age"
attr(adsl$AGEGR1, "label") <- "Age Group"
attr(adsl$SEX, "label") <- "Sex"
attr(adsl$RACE, "label") <- "Race"
attr(adsl$ETHNIC, "label") <- "Ethnicity"
attr(adsl$ARM, "label") <- "Description of Planned Arm"
attr(adsl$TRT01P, "label") <- "Planned Treatment for Period 01"
attr(adsl$TRT01PN, "label") <- "Planned Treatment for Period 01 (N)"
attr(adsl$SAFFL, "label") <- "Safety Population Flag"
attr(adsl$ITTFL, "label") <- "Intent-to-Treat Population Flag"
attr(adsl$EFFFL, "label") <- "Efficacy Population Flag"
attr(adsl$COMPLFL, "label") <- "Completed Study Flag"
attr(adsl$DISCONFL, "label") <- "Discontinued Study Flag"
attr(adsl$DISCONREA, "label") <- "Reason for Discontinuation"
attr(adsl$WEIGHTBL, "label") <- "Baseline Weight (kg)"
attr(adsl$HEIGHTBL, "label") <- "Baseline Height (cm)"
attr(adsl$BMIBL, "label") <- "Baseline BMI (kg/m²)"
attr(adsl$MMSEBL, "label") <- "Baseline MMSE Score"
attr(adsl$ADASCOGBL, "label") <- "Baseline ADAS-Cog (11) Score"
attr(adsl$CIBICBL, "label") <- "Baseline CIBIC+ Score"
attr(adsl$DISDURBL, "label") <- "Disease Duration at Baseline (years)"

# ---- Export ----
cat("Exporting ADSL dataset...\n")
output_dir <- "/workspace/data"
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# Export to Dataset-JSON
tryCatch({
  datasetjson::write_dataset_json(adsl, file.path(output_dir, "adsl.json"))
  cat("Exported to Dataset-JSON format.\n")
}, error = function(e) {
  cat("Dataset-JSON export failed:", e$message, "\n")
  cat("Saving as RDS only.\n")
})

# Also save as RDS for use in other scripts
saveRDS(adsl, file.path(output_dir, "adsl.rds"))
cat("Saved as RDS format.\n")

cat("ADSL generation complete. Records:", nrow(adsl), "\n")
cat("Output saved to:", file.path(output_dir, "adsl.json"), "\n")