# Name: 01_adsl.R
# Description: Generate ADSL (Subject-Level Analysis Dataset)
# Source SDTM: DM, SUPPDM, DS, SUPPDS, EX, SC, VS, QS
# Supports TLGs: T-01, T-02, T-03, T-04, T-17, T-28, T-29, L-01, and as merge key for all others
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

source("/private/var/folders/k_/kns3xnh95lsc57yvx3rhxj100000gn/T/mediforce-local-workspace-hB8wZb/code/00_setup.R")

# ---- Read source data ----
dm     <- read_sdtm("dm")
suppdm <- read_sdtm("suppdm")
ds     <- read_sdtm("ds")
suppds <- read_sdtm("suppds")
ex     <- read_sdtm("ex")
sc     <- read_sdtm("sc")
vs     <- read_sdtm("vs")
qs     <- read_sdtm("qs")
mh     <- read_sdtm("mh")

# ---- Filter randomized subjects only ----
dm_rand <- dm %>%
  filter(ARMCD != "Scrnfail")

# ---- Pivot SUPPDM population flags ----
pop_flags <- suppdm %>%
  select(USUBJID, QNAM, QVAL) %>%
  pivot_wider(names_from = QNAM, values_from = QVAL, values_fill = "N") %>%
  rename(
    ITTFL   = ITT,
    SAFFL   = SAFETY,
    EFFFL   = EFFICACY,
    COMPFL  = COMPLT24,
    COMP8FL = COMPLT8,
    COMP16FL = COMPLT16
  )

# ---- Treatment arm mapping ----
arm_map <- tibble(
  ARMCD    = c("Pbo",    "Xan_Lo",               "Xan_Hi"),
  TRT01A   = c("Placebo","Xanomeline Low Dose",  "Xanomeline High Dose"),
  TRT01AN  = c(1L,       2L,                     3L),
  TRT01P   = c("Placebo","Xanomeline Low Dose",  "Xanomeline High Dose"),
  TRT01PN  = c(1L,       2L,                     3L)
)

# ---- Disposition: completion status and reason ----
# Keep only randomization/disposition events (not screen failure disposition)
disp <- ds %>%
  filter(DSCAT == "DISPOSITION EVENT") %>%
  arrange(USUBJID, desc(DSSTDY)) %>%
  group_by(USUBJID) %>%
  slice(1) %>%
  ungroup() %>%
  mutate(
    EOSSTT  = if_else(DSDECOD == "COMPLETED", "COMPLETED", "DISCONTINUED"),
    DCDECOD = if_else(DSDECOD != "COMPLETED", DSDECOD, NA_character_),
    DCREASCD = if_else(DSDECOD != "COMPLETED", DSTERM, NA_character_)
  ) %>%
  select(USUBJID, EOSSTT, DCDECOD, DCREASCD, DSSTTDY = DSSTDY)

# Check if subject completed Week 26 (Visit 13)
# Use the COMPLETED disposition flag
week26_comp <- ds %>%
  filter(DSDECOD %in% c("COMPLETED", "FINAL LAB VISIT")) %>%
  select(USUBJID) %>%
  distinct() %>%
  mutate(COMP26FL = "Y")

# ---- Education level from SC ----
education <- sc %>%
  filter(SCTESTCD == "EDLEVEL") %>%
  select(USUBJID, EDUCLVL = SCSTRESN) %>%
  distinct()

# ---- Weight and BMI from VS (baseline = Visit 3 = BASELINE) ----
vs_bl_weight <- vs %>%
  filter(VSTESTCD == "WEIGHT", VISIT == "BASELINE") %>%
  group_by(USUBJID) %>%
  slice(1) %>%
  ungroup() %>%
  select(USUBJID, WEIGHTBL = VSSTRESN)

vs_bl_height <- vs %>%
  filter(VSTESTCD == "HEIGHT") %>%
  arrange(USUBJID, VISITNUM) %>%
  group_by(USUBJID) %>%
  slice(1) %>%
  ungroup() %>%
  select(USUBJID, HEIGHTBL = VSSTRESN)

# ---- MMSE at baseline from QS (MINI-MENTAL STATE, SCREENING 1) ----
# MMSE items MMITM01-06, compute total
mmse_total <- qs %>%
  filter(QSCAT == "MINI-MENTAL STATE", VISIT == "SCREENING 1") %>%
  group_by(USUBJID) %>%
  summarise(MMSEBL = sum(QSSTRESN, na.rm = TRUE), .groups = "drop")

# ---- Alzheimer's disease onset from MH ----
ad_onset <- mh %>%
  filter(MHTERM == "ALZHEIMER'S DISEASE" | MHDECOD == "Alzheimer's disease") %>%
  select(USUBJID, MHSTDTC) %>%
  distinct() %>%
  group_by(USUBJID) %>%
  slice(1) %>%
  ungroup()

# ---- Exposure: treatment start/end dates ----
ex_dates <- ex %>%
  group_by(USUBJID) %>%
  summarise(
    TRTSDT_EX = min(as.Date(EXSTDTC), na.rm = TRUE),
    TRTEDT_EX = max(as.Date(EXENDTC), na.rm = TRUE),
    .groups = "drop"
  )

# ---- Build ADSL ----
adsl <- dm_rand %>%
  left_join(arm_map, by = "ARMCD") %>%
  left_join(pop_flags, by = "USUBJID") %>%
  left_join(disp, by = "USUBJID") %>%
  left_join(week26_comp, by = "USUBJID") %>%
  left_join(education, by = "USUBJID") %>%
  left_join(vs_bl_weight, by = "USUBJID") %>%
  left_join(vs_bl_height, by = "USUBJID") %>%
  left_join(mmse_total, by = "USUBJID") %>%
  left_join(ad_onset, by = "USUBJID") %>%
  left_join(ex_dates, by = "USUBJID") %>%
  mutate(
    # Population flags: default to N if missing
    ITTFL    = coalesce(ITTFL,   "N"),
    SAFFL    = coalesce(SAFFL,   "N"),
    EFFFL    = coalesce(EFFFL,   "N"),
    COMPFL   = coalesce(COMPFL,  "N"),
    COMP8FL  = coalesce(COMP8FL, "N"),
    COMP16FL = coalesce(COMP16FL,"N"),
    COMP26FL = coalesce(COMP26FL,"N"),

    # Treatment dates
    TRTSDT = as.Date(RFXSTDTC),
    TRTEDT = as.Date(RFXENDTC),
    # Study dates from DM
    RFSTDTC_DT = as.Date(RFSTDTC),
    RFENDTC_DT = as.Date(RFENDTC),

    # Treatment duration (days)
    TRTDUR = as.integer(TRTEDT - TRTSDT + 1),

    # Age groups
    AGEGR1  = case_when(
      AGE < 65            ~ "<65",
      AGE >= 65 & AGE <= 80 ~ "65-80",
      AGE > 80            ~ ">80"
    ),
    AGEGR1N = case_when(
      AGEGR1 == "<65"  ~ 1L,
      AGEGR1 == "65-80" ~ 2L,
      AGEGR1 == ">80" ~ 3L
    ),

    # Sex numeric
    SEXN = case_when(
      SEX == "M" ~ 1L,
      SEX == "F" ~ 2L,
      TRUE ~ NA_integer_
    ),

    # Race numeric
    RACEN = case_when(
      RACE == "WHITE"                                    ~ 1L,
      RACE == "BLACK OR AFRICAN AMERICAN"               ~ 2L,
      RACE == "AMERICAN INDIAN OR ALASKA NATIVE"        ~ 3L,
      RACE == "ASIAN"                                   ~ 4L,
      RACE == "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER" ~ 5L,
      RACE == "MULTIPLE"                                ~ 6L,
      TRUE                                              ~ 99L
    ),

    # BMI at baseline
    BMIBL = if_else(
      !is.na(WEIGHTBL) & !is.na(HEIGHTBL) & HEIGHTBL > 0,
      round(WEIGHTBL / (HEIGHTBL / 100)^2, 1),
      NA_real_
    ),

    # Disease onset and duration
    DISONSDT = as.Date(substr(MHSTDTC, 1, 10)),
    DURDIS   = if_else(
      !is.na(DISONSDT) & !is.na(TRTSDT),
      as.numeric(difftime(TRTSDT, DISONSDT, units = "days")) / 365.25,
      NA_real_
    ),
    DURDSGR1 = case_when(
      is.na(DURDIS) ~ NA_character_,
      DURDIS < 1    ~ "<1 year",
      DURDIS < 2    ~ "1-<2 years",
      TRUE          ~ ">=2 years"
    ),

    # Site
    SITEID   = SITEID,
    POOLSIT1 = SITEID,  # simplified; no pooling logic applied

    # Study identifiers
    STUDYID  = STUDYID,
    DOMAIN   = "ADSL",

    # Completer flags
    EOSSTT   = coalesce(EOSSTT, "DISCONTINUED"),
  ) %>%
  select(
    STUDYID, USUBJID, SUBJID, SITEID, POOLSIT1, COUNTRY,
    AGE, AGEU, AGEGR1, AGEGR1N,
    SEX, SEXN, RACE, RACEN, ETHNIC,
    ARMCD, ARM, TRT01A, TRT01AN, TRT01P, TRT01PN,
    ACTARMCD, ACTARM,
    RFSTDTC, RFENDTC, RFXSTDTC, RFXENDTC,
    TRTSDT, TRTEDT, TRTDUR,
    ITTFL, SAFFL, EFFFL, COMPFL, COMP8FL, COMP16FL, COMP26FL,
    EOSSTT, DCDECOD, DCREASCD,
    MMSEBL, EDUCLVL,
    HEIGHTBL, WEIGHTBL, BMIBL,
    DISONSDT, DURDIS, DURDSGR1
  )

# ---- Validate ----
cat("ADSL rows:", nrow(adsl), "\n")
cat("ADSL unique subjects:", n_distinct(adsl$USUBJID), "\n")
cat("Treatment groups:\n")
print(table(adsl$TRT01A))
cat("\nITTFL:\n")
print(table(adsl$ITTFL))
cat("\nSAFFL:\n")
print(table(adsl$SAFFL))
cat("\nEFFFL:\n")
print(table(adsl$EFFFL))
cat("\nCOMPFL (Week 24):\n")
print(table(adsl$COMPFL))
cat("\nEOSSTT:\n")
print(table(adsl$EOSSTT))

# ---- Export ----
write_adam(adsl, "adsl")
saveRDS(adsl, file.path(ADAM_DIR, "adsl.rds"))
