# Name: 02_admh.R
# Description: Generate ADMH dataset for CDISCPILOT01
# Source SDTM: MH, ADSL
# Supports TLGs: T-14.1.3
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

# ---- Setup ----
library(admiral)
library(dplyr)
library(lubridate)
library(stringr)

# Source helper functions
source("/workspace/code/00_setup.R")

# ---- Read source data ----
cat("Reading source data...\n")
mh <- read_sdtm("MH")
adsl <- readRDS("/workspace/data/adsl.rds")

# ---- Prepare MH data ----
cat("Preparing MH data...\n")
admh <- mh %>%
  mutate(
    MHSEQ = as.numeric(MHSEQ),
    MHTERM = MHTERM,
    MHDECOD = MHDECOD,
    MHBODSYS = MHBODSYS,
    MHCAT = MHCAT,
    MHSCAT = MHSCAT,
    MHPRESP = MHPRESP,
    MHOCCUR = MHOCCUR,
    MHSTDTC = MHSTDTC,
    MHENDTC = MHENDTC
  ) %>%
  select(
    USUBJID, MHSEQ, MHTERM, MHDECOD, MHBODSYS,
    MHCAT, MHSCAT, MHPRESP, MHOCCUR,
    MHSTDTC, MHENDTC
  )

# ---- Add treatment variables ----
cat("Adding treatment variables...\n")
admh_final <- admh %>%
  left_join(
    adsl %>% select(USUBJID, TRT01P, TRT01PN, SAFFL),
    by = "USUBJID"
  ) %>%
  mutate(
    TRTP = TRT01P,
    TRTPN = TRT01PN
  ) %>%
  filter(SAFFL == "Y") %>%  # Keep only safety population
  select(-SAFFL)

# ---- Add labels ----
cat("Adding variable labels...\n")
attr(admh_final$USUBJID, "label") <- "Unique Subject Identifier"
attr(admh_final$MHSEQ, "label") <- "Sequence Number"
attr(admh_final$MHTERM, "label") <- "Reported Term for the Medical History"
attr(admh_final$MHDECOD, "label") <- "Dictionary-Derived Term"
attr(admh_final$MHBODSYS, "label") <- "Body System or Organ Class"
attr(admh_final$MHCAT, "label") <- "Category for Medical History"
attr(admh_final$MHSCAT, "label") <- "Subcategory for Medical History"
attr(admh_final$MHPRESP, "label") <- "Medical History Pre-specified"
attr(admh_final$MHOCCUR, "label") <- "Medical History Occurrence"
attr(admh_final$MHSTDTC, "label") <- "Start Date/Time of Medical History"
attr(admh_final$MHENDTC, "label") <- "End Date/Time of Medical History"
attr(admh_final$TRTP, "label") <- "Planned Treatment"
attr(admh_final$TRTPN, "label") <- "Planned Treatment (N)"

# ---- Export ----
cat("Exporting ADMH dataset...\n")
output_dir <- "/workspace/data"
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# Export to Dataset-JSON
tryCatch({
  datasetjson::write_dataset_json(\1, file.path(output_dir, "\2"))
  cat("Exported to Dataset-JSON format.\\n")
}, error = function(e) {
  cat("Dataset-JSON export failed:", e$message, "\\n")
  cat("Saving as RDS only.\\n")
})
saveRDS(\1, file.path(output_dir, "\3"))
cat("Saved as RDS format.\\n")

cat("ADMH generation complete. Records:", nrow(admh_final), "\n")
cat("Output saved to:", file.path(output_dir, "admh.json"), "\n")