# Name: 02_adqsadas.R
# Description: Generate ADQSADAS (ADAS-Cog 11 Analysis Dataset)
# Source SDTM: QS, ADSL
# Supports TLGs: T-05, T-07, T-09, T-11, T-12, T-13, T-14, T-15
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

source("/private/var/folders/k_/kns3xnh95lsc57yvx3rhxj100000gn/T/mediforce-local-workspace-hB8wZb/code/00_setup.R")

# ---- Read source data ----
qs   <- read_sdtm("qs")
adsl <- readRDS(file.path(ADAM_DIR, "adsl.rds"))

# ---- Filter QS to ADAS-Cog ----
# ADAS-Cog (11) uses items ACITM01-ACITM11 and total ACTOT
# ACITM12-ACITM14 are the 3 additional items for ADAS-Cog (14)
adas_items11 <- paste0("ACITM", sprintf("%02d", 1:11))

adas_raw <- qs %>%
  filter(QSCAT == "ALZHEIMER'S DISEASE ASSESSMENT SCALE",
         QSTESTCD %in% c(adas_items11, "ACTOT")) %>%
  mutate(
    QSDTC_DT = as.Date(substr(QSDTC, 1, 10)),
    VISITNUM  = as.numeric(VISITNUM)
  )

# ---- Visit windowing for ADAS-Cog analysis visits ----
# Windows per SAP:
#   Baseline: day < 1 or day = 1 (target day 1)
#   Week 8:   days 2-84 (target 56)
#   Week 16:  days 85-140 (target 112)
#   Week 24:  days > 140 (target 168)

adas_windowed <- adas_raw %>%
  mutate(
    AVISIT = case_when(
      VISIT == "BASELINE"                        ~ "Baseline",
      QSDY >= 2  & QSDY <= 84   | VISIT %in% c("WEEK 8")  ~ "Week 8",
      QSDY >= 85 & QSDY <= 140  | VISIT %in% c("WEEK 16") ~ "Week 16",
      QSDY > 140                | VISIT %in% c("WEEK 24", "RETRIEVAL") ~ "Week 24",
      TRUE ~ VISIT
    ),
    AVISITN = case_when(
      AVISIT == "Baseline" ~ 0L,
      AVISIT == "Week 8"   ~ 8L,
      AVISIT == "Week 16"  ~ 16L,
      AVISIT == "Week 24"  ~ 24L,
      TRUE ~ NA_integer_
    )
  ) %>%
  filter(!is.na(AVISITN))

# ---- Select one record per subject per item per analysis visit ----
# If multiple records in window, pick closest to target day;
# if equidistant, pick the one prior to target
target_days <- c("Baseline" = 1, "Week 8" = 56, "Week 16" = 112, "Week 24" = 168)

adas_sel <- adas_windowed %>%
  mutate(
    TARGET_DY = target_days[AVISIT],
    DIST_DY   = abs(QSDY - TARGET_DY),
    PREFTIE   = if_else(QSDY <= TARGET_DY, 0L, 1L)
  ) %>%
  group_by(USUBJID, QSTESTCD, AVISIT) %>%
  arrange(DIST_DY, PREFTIE) %>%
  slice(1) %>%
  ungroup()

# ---- Compute ADAS-Cog (11) total score ----
# From individual items (sum of ACITM01-11)
# Also include pre-calculated ACTOT if available
adas_item_scores <- adas_sel %>%
  filter(QSTESTCD %in% adas_items11) %>%
  group_by(USUBJID, AVISIT, AVISITN) %>%
  summarise(
    N_ITEMS  = sum(!is.na(QSSTRESN)),
    AVAL_RAW = sum(QSSTRESN, na.rm = TRUE),
    # SAP scoring: if any items missing, adjust by ratio if <= 30% missing (i.e. <=3 of 11)
    N_MISSING = sum(is.na(QSSTRESN)),
    .groups = "drop"
  ) %>%
  mutate(
    # If >30% items missing (>3 of 11), set total to missing
    AVAL = if_else(
      N_MISSING > 3,
      NA_real_,
      AVAL_RAW * (70 / (70 - N_MISSING * (70/11)))  # adjusted scoring
    )
  )

# Actually SAP says: if >30% items missing, set to missing; otherwise
# multiply observed sum by (full range / observed range) to adjust
# ADAS items range varies by item; simpler approach: use ACTOT if available
adas_totals <- adas_sel %>%
  filter(QSTESTCD == "ACTOT") %>%
  select(USUBJID, AVISIT, AVISITN, QSDTC_DT, QSDY, AVAL_ACTOT = QSSTRESN)

# Prefer ACTOT; fallback to sum of items
adas_aval <- adas_totals %>%
  full_join(
    adas_item_scores %>% select(USUBJID, AVISIT, AVISITN, AVAL_ITEMS = AVAL),
    by = c("USUBJID", "AVISIT", "AVISITN")
  ) %>%
  mutate(
    AVAL = coalesce(AVAL_ACTOT, AVAL_ITEMS)
  )

# ---- Build long-format ADQSADAS with one row per subject per analysis visit ----
# Use complete grid of subjects × visits (critical for LOCF)
adqsadas_base <- adsl %>%
  filter(EFFFL == "Y") %>%
  select(USUBJID, STUDYID, TRT01A, TRT01AN, SAFFL, ITTFL, EFFFL, COMPFL, TRTSDT, TRTEDT,
         SITEID, AGE, AGEGR1, SEX, RACE, ARMCD) %>%
  mutate(
    PARAMCD = "ACTOT11",
    PARAM   = "ADAS-Cog (11) Total Score",
    PARAMN  = 1L
  )

# All analysis visits
all_visits <- tibble(
  AVISIT  = c("Baseline", "Week 8", "Week 16", "Week 24"),
  AVISITN = c(0L, 8L, 16L, 24L)
)

# Create complete grid: every subject × every visit
adqsadas_grid <- adqsadas_base %>%
  crossing(all_visits)

# Join observed AVAL values
adqsadas <- adqsadas_grid %>%
  left_join(
    adas_aval %>% select(USUBJID, AVISIT, AVISITN, AVAL, QSDTC_DT, QSDY),
    by = c("USUBJID", "AVISIT", "AVISITN")
  )

# ---- Derive baseline, change from baseline ----
baseline_vals <- adqsadas %>%
  filter(AVISIT == "Baseline") %>%
  select(USUBJID, PARAMCD, BASE = AVAL)

adqsadas <- adqsadas %>%
  left_join(baseline_vals, by = c("USUBJID", "PARAMCD")) %>%
  mutate(
    CHG    = if_else(!is.na(AVAL) & !is.na(BASE) & AVISITN > 0, AVAL - BASE, NA_real_),
    PCHG   = if_else(!is.na(CHG) & !is.na(BASE) & BASE != 0, CHG / BASE * 100, NA_real_),
    ABLFL  = if_else(AVISIT == "Baseline", "Y", NA_character_),
    ANL01FL = "Y"  # LOCF flag placeholder - set for observed
  )

# ---- LOCF imputation ----
# Apply LOCF for post-baseline analysis visits (Weeks 8, 16, 24)
# If AVAL is missing at a post-baseline visit, use last non-missing AVAL
adqsadas_locf <- adqsadas %>%
  arrange(USUBJID, PARAMCD, AVISITN) %>%
  group_by(USUBJID, PARAMCD) %>%
  mutate(
    AVAL_LOCF = {
      av <- AVAL
      for (i in seq_along(av)) {
        if (i > 1 && AVISITN[i] > 0 && is.na(av[i])) {
          av[i] <- av[i-1]
        }
      }
      av
    }
  ) %>%
  ungroup() %>%
  mutate(
    CHG_LOCF = if_else(AVISITN > 0, AVAL_LOCF - BASE, NA_real_),
    ANL01FL  = if_else(AVISITN > 0 & !is.na(AVAL_LOCF), "Y", ANL01FL)
  )

# Create final ADQSADAS with both observed and LOCF values
adqsadas_final <- adqsadas_locf %>%
  mutate(
    DTYPE  = if_else(is.na(AVAL) & !is.na(AVAL_LOCF) & AVISITN > 0, "LOCF", NA_character_),
    AVAL   = coalesce(AVAL, AVAL_LOCF),  # replace with LOCF where needed
    CHG    = if_else(AVISITN > 0, AVAL - BASE, NA_real_),
    ADT    = QSDTC_DT,
    ADY    = QSDY,
    DOMAIN = "ADQS"
  ) %>%
  select(
    STUDYID, USUBJID, DOMAIN, PARAMCD, PARAM, PARAMN,
    AVISIT, AVISITN, ADT, ADY,
    AVAL, BASE, CHG, PCHG, DTYPE, ABLFL, ANL01FL,
    TRT01A, TRT01AN, SAFFL, ITTFL, EFFFL, COMPFL,
    SITEID, AGE, AGEGR1, SEX, RACE, ARMCD,
    TRTSDT, TRTEDT
  ) %>%
  arrange(USUBJID, PARAMCD, AVISITN)

# ---- Validate ----
cat("ADQSADAS rows:", nrow(adqsadas_final), "\n")
cat("Subjects:", n_distinct(adqsadas_final$USUBJID), "\n")
cat("Visits:\n")
print(table(adqsadas_final$AVISIT, useNA = "ifany"))
cat("AVAL non-missing:\n")
cat("  Baseline:", sum(!is.na(adqsadas_final$AVAL[adqsadas_final$AVISIT=="Baseline"])), "\n")
cat("  Week 8:", sum(!is.na(adqsadas_final$AVAL[adqsadas_final$AVISIT=="Week 8"])), "\n")
cat("  Week 16:", sum(!is.na(adqsadas_final$AVAL[adqsadas_final$AVISIT=="Week 16"])), "\n")
cat("  Week 24:", sum(!is.na(adqsadas_final$AVAL[adqsadas_final$AVISIT=="Week 24"])), "\n")
cat("DTYPE LOCF count:", sum(adqsadas_final$DTYPE=="LOCF", na.rm=TRUE), "\n")

# ---- Export ----
write_adam(adqsadas_final, "adqsadas")
saveRDS(adqsadas_final, file.path(ADAM_DIR, "adqsadas.rds"))
