# Name: 03_adcm.R
# Description: Generate ADCM dataset for CDISCPILOT01
# Source SDTM: CM, ADSL
# Supports TLGs: T-14.1.4, L-16.1.2
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

# ---- Setup ----
library(admiral)
library(dplyr)
library(lubridate)
library(stringr)

# Source helper functions
source("/workspace/code/00_setup.R")

# ---- Read source data ----
cat("Reading source data...\n")
cm <- read_sdtm("CM")
adsl <- readRDS("/workspace/data/adsl.rds")

# ---- Prepare CM data ----
cat("Preparing CM data...\n")
adcm <- cm %>%
  mutate(
    CMSEQ = as.numeric(CMSEQ),
    CMTRT = CMTRT,
    CMDECOD = CMDECOD,
    CMCAT = CMCAT,
    CMSCAT = CMSCAT,
    CMPRESP = CMPRESP,
    CMOCCUR = CMOCCUR,
    CMSTDTC = CMSTDTC,
    CMENDTC = CMENDTC,
    CMROUTE = CMROUTE,
    CMDOSE = as.numeric(CMDOSE),
    CMDOSU = CMDOSU,
    CMFRQ = CMFRQ
  ) %>%
  select(
    USUBJID, CMSEQ, CMTRT, CMDECOD, CMCAT, CMSCAT,
    CMPRESP, CMOCCUR, CMSTDTC, CMENDTC,
    CMROUTE, CMDOSE, CMDOSU, CMFRQ
  )

# ---- Derive prior/concomitant flag ----
cat("Deriving prior/concomitant flag...\n")
adcm <- adcm %>%
  left_join(
    adsl %>% select(USUBJID, RFXSTDTC),
    by = "USUBJID"
  ) %>%
  mutate(
    CMPRIOR = ifelse(
      !is.na(CMSTDTC) & CMSTDTC < RFXSTDTC,
      "PRIOR",
      "CONCOMITANT"
    )
  ) %>%
  select(-RFXSTDTC)

# ---- Add treatment variables ----
cat("Adding treatment variables...\n")
adcm_final <- adcm %>%
  left_join(
    adsl %>% select(USUBJID, TRT01P, TRT01PN, SAFFL),
    by = "USUBJID"
  ) %>%
  mutate(
    TRTP = TRT01P,
    TRTPN = TRT01PN
  ) %>%
  filter(SAFFL == "Y") %>%  # Keep only safety population
  select(-SAFFL)

# ---- Add labels ----
cat("Adding variable labels...\n")
attr(adcm_final$USUBJID, "label") <- "Unique Subject Identifier"
attr(adcm_final$CMSEQ, "label") <- "Sequence Number"
attr(adcm_final$CMTRT, "label") <- "Reported Name of Drug, Med, or Therapy"
attr(adcm_final$CMDECOD, "label") <- "Standardized Medication Name"
attr(adcm_final$CMCAT, "label") <- "Category for Medication"
attr(adcm_final$CMSCAT, "label") <- "Subcategory for Medication"
attr(adcm_final$CMPRESP, "label") <- "Pre-specified Medication"
attr(adcm_final$CMOCCUR, "label") <- "Concomitant Medication Occurrence"
attr(adcm_final$CMSTDTC, "label") <- "Start Date/Time of Medication"
attr(adcm_final$CMENDTC, "label") <- "End Date/Time of Medication"
attr(adcm_final$CMROUTE, "label") <- "Route of Administration"
attr(adcm_final$CMDOSE, "label") <- "Dose per Administration"
attr(adcm_final$CMDOSU, "label") <- "Dose Units"
attr(adcm_final$CMFRQ, "label") <- "Dosing Frequency per Interval"
attr(adcm_final$CMPRIOR, "label") <- "Prior/Concomitant Medication"
attr(adcm_final$TRTP, "label") <- "Planned Treatment"
attr(adcm_final$TRTPN, "label") <- "Planned Treatment (N)"

# ---- Export ----
cat("Exporting ADCM dataset...\n")
output_dir <- "/workspace/data"
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# Export to Dataset-JSON
tryCatch({
  datasetjson::write_dataset_json(\1, file.path(output_dir, "\2"))
  cat("Exported to Dataset-JSON format.\\n")
}, error = function(e) {
  cat("Dataset-JSON export failed:", e$message, "\\n")
  cat("Saving as RDS only.\\n")
})
saveRDS(\1, file.path(output_dir, "\3"))
cat("Saved as RDS format.\\n")

cat("ADCM generation complete. Records:", nrow(adcm_final), "\n")
cat("Output saved to:", file.path(output_dir, "adcm.json"), "\n")