# Name: 03_adqscibc.R
# Description: Generate ADQSCIBC (CIBIC+ Analysis Dataset)
# Source SDTM: QS, ADSL
# Supports TLGs: T-06, T-08, T-10, T-30
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

source("/private/var/folders/k_/kns3xnh95lsc57yvx3rhxj100000gn/T/mediforce-local-workspace-hB8wZb/code/00_setup.R")

# ---- Read source data ----
qs   <- read_sdtm("qs")
adsl <- readRDS(file.path(ADAM_DIR, "adsl.rds"))

# ---- Filter QS to CIBIC+ ----
cibic_raw <- qs %>%
  filter(QSCAT == "CLINICIAN'S INTERVIEW-BASED IMPRESSION OF CHANGE (CIBIC+)",
         QSTESTCD == "CIBIC") %>%
  mutate(
    QSDTC_DT = as.Date(substr(QSDTC, 1, 10)),
    VISITNUM  = as.numeric(VISITNUM)
  )

# ---- Visit windowing for CIBIC+ ----
# SAP windows:
#   Week 2:  days 2-21    (target 14)
#   Week 4:  days 22-42   (target 28)
#   Week 6:  days 43-63   (target 42)
#   Week 8:  days 43-84   (target 56)  [Note: SAP specifies detailed windows]
#   Week 12: days 85-112  (target 84) -- approximated
#   Week 16: days 85-140  (target 112)
#   Week 20: days 141-154 (target 140)
#   Week 24: days >140    (target 168)
#   Week 26: days >175    (target 182)
# Note: CIBIC+ does not have a Baseline value (it IS the change from baseline)
# The first CIBIC+ is at Week 2

cibic_windowed <- cibic_raw %>%
  mutate(
    AVISIT = case_when(
      VISIT == "WEEK 2"                         ~ "Week 2",
      VISIT == "WEEK 4"                         ~ "Week 4",
      VISIT == "WEEK 6"                         ~ "Week 6",
      VISIT == "WEEK 8"                         ~ "Week 8",
      VISIT == "WEEK 12"                        ~ "Week 12",
      VISIT == "WEEK 16"                        ~ "Week 16",
      VISIT == "WEEK 20"                        ~ "Week 20",
      VISIT %in% c("WEEK 24", "RETRIEVAL")      ~ "Week 24",
      VISIT == "WEEK 26"                        ~ "Week 26",
      TRUE ~ VISIT
    ),
    AVISITN = case_when(
      AVISIT == "Week 2"  ~ 2L,
      AVISIT == "Week 4"  ~ 4L,
      AVISIT == "Week 6"  ~ 6L,
      AVISIT == "Week 8"  ~ 8L,
      AVISIT == "Week 12" ~ 12L,
      AVISIT == "Week 16" ~ 16L,
      AVISIT == "Week 20" ~ 20L,
      AVISIT == "Week 24" ~ 24L,
      AVISIT == "Week 26" ~ 26L,
      TRUE ~ NA_integer_
    )
  ) %>%
  filter(!is.na(AVISITN))

# ---- Select one record per subject per analysis visit ----
target_days_cibic <- c("Week 2" = 14, "Week 4" = 28, "Week 6" = 42,
                       "Week 8" = 56, "Week 12" = 84, "Week 16" = 112,
                       "Week 20" = 140, "Week 24" = 168, "Week 26" = 182)

cibic_sel <- cibic_windowed %>%
  mutate(
    TARGET_DY = target_days_cibic[AVISIT],
    DIST_DY   = abs(QSDY - TARGET_DY),
    PREFTIE   = if_else(QSDY <= TARGET_DY, 0L, 1L)
  ) %>%
  group_by(USUBJID, AVISIT) %>%
  arrange(DIST_DY, PREFTIE) %>%
  slice(1) %>%
  ungroup()

# ---- Build ADQSCIBC ----
adsl_sub <- adsl %>%
  filter(EFFFL == "Y") %>%
  select(USUBJID, STUDYID, TRT01A, TRT01AN, SAFFL, ITTFL, EFFFL, COMPFL, TRTSDT, TRTEDT,
         SITEID, AGE, AGEGR1, SEX, RACE, ARMCD)

# Build complete grid for key LOCF analysis visits (Weeks 8, 16, 24) plus all observed
all_cibic_visits <- tibble(
  AVISIT  = c("Week 2","Week 4","Week 6","Week 8","Week 12","Week 16","Week 20","Week 24","Week 26"),
  AVISITN = c(2L, 4L, 6L, 8L, 12L, 16L, 20L, 24L, 26L)
)

cibic_observed <- cibic_sel %>%
  select(USUBJID, AVISIT, AVISITN, AVAL = QSSTRESN, ADT = QSDTC_DT, ADY = QSDY)

adqscibc <- adsl_sub %>%
  crossing(all_cibic_visits) %>%
  left_join(cibic_observed, by = c("USUBJID", "AVISIT", "AVISITN")) %>%
  mutate(
    PARAMCD = "CIBIC",
    PARAM   = "CIBIC+ Global Score",
    PARAMN  = 1L,
    DOMAIN  = "ADQS",
    # CIBIC+ is already a change-from-baseline measure (1=markedly improved to 7=markedly worse)
    # No BASE or CHG derivation needed; analysis is on AVAL directly
    ANL01FL = "Y"
  )

# LOCF imputation for CIBIC+ at Weeks 8, 16, 24
cibic_locf_visits <- c("Week 8", "Week 16", "Week 24")

adqscibc_locf <- adqscibc %>%
  arrange(USUBJID, PARAMCD, AVISITN) %>%
  group_by(USUBJID, PARAMCD) %>%
  mutate(
    AVAL_LOCF = {
      av <- AVAL
      for (i in seq_along(av)) {
        if (i > 1 && is.na(av[i])) {
          av[i] <- av[i-1]
        }
      }
      av
    }
  ) %>%
  ungroup() %>%
  mutate(
    DTYPE = if_else(is.na(AVAL) & !is.na(AVAL_LOCF) & AVISIT %in% cibic_locf_visits,
                    "LOCF", NA_character_),
    AVAL  = coalesce(AVAL, AVAL_LOCF)
  ) %>%
  select(
    STUDYID, USUBJID, DOMAIN, PARAMCD, PARAM, PARAMN,
    AVISIT, AVISITN, ADT, ADY,
    AVAL, DTYPE, ANL01FL,
    TRT01A, TRT01AN, SAFFL, ITTFL, EFFFL, COMPFL,
    SITEID, AGE, AGEGR1, SEX, RACE, ARMCD,
    TRTSDT, TRTEDT
  ) %>%
  arrange(USUBJID, PARAMCD, AVISITN)

# ---- Validate ----
cat("ADQSCIBC rows:", nrow(adqscibc_locf), "\n")
cat("Subjects:", n_distinct(adqscibc_locf$USUBJID), "\n")
cat("Visits:\n")
print(table(adqscibc_locf$AVISIT, useNA = "ifany"))
cat("AVAL summary at Week 24:\n")
print(summary(adqscibc_locf$AVAL[adqscibc_locf$AVISIT == "Week 24"]))
cat("DTYPE LOCF count:", sum(adqscibc_locf$DTYPE == "LOCF", na.rm = TRUE), "\n")

# ---- Export ----
write_adam(adqscibc_locf, "adqscibc")
saveRDS(adqscibc_locf, file.path(ADAM_DIR, "adqscibc.rds"))
