# Name: 04_adqsnpix.R
# Description: Generate ADQSNPIX (NPI-X Analysis Dataset)
# Source SDTM: QS, ADSL
# Supports TLGs: T-16
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

source("/private/var/folders/k_/kns3xnh95lsc57yvx3rhxj100000gn/T/mediforce-local-workspace-hB8wZb/code/00_setup.R")

# ---- Read source data ----
qs   <- read_sdtm("qs")
adsl <- readRDS(file.path(ADAM_DIR, "adsl.rds"))

# ---- Filter QS to NPI-X ----
# 12 domains, but 9-domain score (exclude: 06=Euphoria, 11=Night-time, 12=Appetite)
# Domain score = frequency × severity = NPITM??V variables
# Items: NPITM01-12 (main), NPITM??D (distress), NPITM??F (freq), NPITM??S (sev), NPITM??V (domain total)
# NPTOT = pre-calculated total

npix_incl_domains <- paste0("NPITM", sprintf("%02d", c(1:5, 7:10)), "V")  # 9-domain scores
npix_total_cd     <- "NPTOT"

npix_raw <- qs %>%
  filter(QSCAT == "NEUROPSYCHIATRIC INVENTORY - REVISED (NPI-X)",
         QSTESTCD %in% c(npix_incl_domains, npix_total_cd)) %>%
  mutate(
    QSDTC_DT = as.Date(substr(QSDTC, 1, 10)),
    VISITNUM  = as.numeric(VISITNUM)
  )

# ---- Visit assignment ----
# NPI-X collected at biweekly visits; analysis windows from SAP
npix_windowed <- npix_raw %>%
  mutate(
    AVISIT = case_when(
      VISIT == "BASELINE"                        ~ "Baseline",
      VISIT %in% c("WEEK 2","WEEK 4","WEEK 6",
                   "WEEK 8","WEEK 10 (T)","WEEK 12",
                   "WEEK 14 (T)","WEEK 16","WEEK 18 (T)",
                   "WEEK 20","WEEK 22 (T)","WEEK 24",
                   "RETRIEVAL")                 ~ VISIT,
      VISIT == "WEEK 4"                          ~ "Week 4",
      VISIT == "WEEK 6"                          ~ "Week 6",
      VISIT == "WEEK 8"                          ~ "Week 8",
      TRUE ~ VISIT
    ),
    # Normalize visit names
    AVISIT = str_to_title(gsub(" \\(T\\)", "", AVISIT)),
    AVISITN = case_when(
      grepl("Baseline|Baseline", AVISIT)    ~ 0L,
      AVISIT == "Week 2"   ~ 2L,
      AVISIT == "Week 4"   ~ 4L,
      AVISIT == "Week 6"   ~ 6L,
      AVISIT == "Week 8"   ~ 8L,
      AVISIT == "Week 10"  ~ 10L,
      AVISIT == "Week 12"  ~ 12L,
      AVISIT == "Week 14"  ~ 14L,
      AVISIT == "Week 16"  ~ 16L,
      AVISIT == "Week 18"  ~ 18L,
      AVISIT == "Week 20"  ~ 20L,
      AVISIT == "Week 22"  ~ 22L,
      AVISIT == "Week 24"  ~ 24L,
      TRUE ~ NA_integer_
    )
  ) %>%
  filter(!is.na(AVISITN))

# ---- Compute 9-domain NPI-X total score ----
# Use NPTOT if available; or sum domain scores
npix_total_raw <- npix_windowed %>%
  filter(QSTESTCD == npix_total_cd) %>%
  select(USUBJID, AVISIT, AVISITN, QSDTC_DT, QSDY, AVAL_NPTOT = QSSTRESN)

# Domain sum (9 domains)
npix_domain_sum <- npix_windowed %>%
  filter(QSTESTCD %in% npix_incl_domains) %>%
  group_by(USUBJID, AVISIT, AVISITN) %>%
  summarise(
    AVAL_DOM9 = if (sum(!is.na(QSSTRESN)) > 0) sum(QSSTRESN, na.rm = TRUE) else NA_real_,
    .groups = "drop"
  )

# Combine (prefer NPTOT; note NPTOT may include all 12 domains, so we prefer domain sum for 9-domain score)
npix_aval <- npix_total_raw %>%
  full_join(npix_domain_sum, by = c("USUBJID", "AVISIT", "AVISITN")) %>%
  mutate(
    # Use 9-domain sum as primary (per SAP: 9-domain NPI-X excluding sleep/appetite/euphoria)
    AVAL = coalesce(AVAL_DOM9, AVAL_NPTOT)
  )

# ---- Build ADQSNPIX ----
adsl_sub <- adsl %>%
  filter(EFFFL == "Y") %>%
  select(USUBJID, STUDYID, TRT01A, TRT01AN, SAFFL, ITTFL, EFFFL, COMPFL, TRTSDT, TRTEDT,
         SITEID, AGE, AGEGR1, SEX, RACE, ARMCD)

adqsnpix <- adsl_sub %>%
  left_join(npix_aval, by = "USUBJID") %>%
  filter(!is.na(AVISIT)) %>%
  mutate(
    PARAMCD = "NPTOT9",
    PARAM   = "NPI-X 9-Domain Total Score",
    PARAMN  = 1L,
    DOMAIN  = "ADQS"
  )

# ---- Derive baseline and change ----
baseline_vals <- adqsnpix %>%
  filter(AVISITN == 0) %>%
  select(USUBJID, PARAMCD, BASE = AVAL)

adqsnpix <- adqsnpix %>%
  left_join(baseline_vals, by = c("USUBJID", "PARAMCD")) %>%
  mutate(
    CHG   = if_else(AVISITN > 0 & !is.na(AVAL) & !is.na(BASE), AVAL - BASE, NA_real_),
    ABLFL = if_else(AVISITN == 0, "Y", NA_character_),
    ADT   = QSDTC_DT,
    ADY   = QSDY
  )

# ---- Compute mean NPI-X over Weeks 4-24 (analysis endpoint for T-16) ----
# Mean of Weeks 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24 (observed windowed, no LOCF per SAP)
npix_weeks_4_24 <- adqsnpix %>%
  filter(AVISITN %in% c(4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24)) %>%
  group_by(USUBJID) %>%
  summarise(
    AVAL_MEAN = mean(AVAL, na.rm = TRUE),
    N_WEEKS   = sum(!is.na(AVAL)),
    .groups   = "drop"
  ) %>%
  mutate(
    AVAL_MEAN = if_else(N_WEEKS > 0, AVAL_MEAN, NA_real_)
  )

# Add mean parameter record
npix_mean_param <- adsl_sub %>%
  left_join(npix_weeks_4_24, by = "USUBJID") %>%
  left_join(
    adqsnpix %>% filter(AVISITN == 0) %>% select(USUBJID, BASE = AVAL),
    by = "USUBJID"
  ) %>%
  mutate(
    PARAMCD = "NPTMN24",
    PARAM   = "Mean NPI-X 9-Domain Total Score (Weeks 4-24)",
    PARAMN  = 2L,
    DOMAIN  = "ADQS",
    AVISIT  = "Weeks 4-24 Mean",
    AVISITN = 99L,
    AVAL    = AVAL_MEAN,
    CHG     = if_else(!is.na(AVAL_MEAN) & !is.na(BASE), AVAL_MEAN - BASE, NA_real_),
    ABLFL   = NA_character_,
    ADT     = as.Date(NA),
    ADY     = NA_integer_
  ) %>%
  select(-AVAL_MEAN, -N_WEEKS)

# Combine all records
adqsnpix_final <- bind_rows(adqsnpix, npix_mean_param) %>%
  select(
    STUDYID, USUBJID, DOMAIN, PARAMCD, PARAM, PARAMN,
    AVISIT, AVISITN, ADT, ADY,
    AVAL, BASE, CHG, ABLFL,
    TRT01A, TRT01AN, SAFFL, ITTFL, EFFFL, COMPFL,
    SITEID, AGE, AGEGR1, SEX, RACE, ARMCD,
    TRTSDT, TRTEDT
  ) %>%
  arrange(USUBJID, PARAMN, AVISITN)

# ---- Validate ----
cat("ADQSNPIX rows:", nrow(adqsnpix_final), "\n")
cat("Subjects:", n_distinct(adqsnpix_final$USUBJID), "\n")
cat("PARAMCD:\n")
print(table(adqsnpix_final$PARAMCD))
cat("\nAVAL summary at Baseline:\n")
print(summary(adqsnpix_final$AVAL[adqsnpix_final$AVISITN == 0 & adqsnpix_final$PARAMCD == "NPTOT9"]))

# ---- Export ----
write_adam(adqsnpix_final, "adqsnpix")
saveRDS(adqsnpix_final, file.path(ADAM_DIR, "adqsnpix.rds"))
