# Name: 04_adex.R
# Description: Generate ADEX dataset for CDISCPILOT01
# Source SDTM: EX, ADSL
# Supports TLGs: T-14.1.5
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

# ---- Setup ----
library(admiral)
library(dplyr)
library(lubridate)
library(stringr)

# Source helper functions
source("/workspace/code/00_setup.R")

# ---- Read source data ----
cat("Reading source data...\n")
ex <- read_sdtm("EX")
adsl <- readRDS("/workspace/data/adsl.rds")

# ---- Prepare EX data ----
cat("Preparing EX data...\n")
adex <- ex %>%
  mutate(
    EXSEQ = as.numeric(EXSEQ),
    EXTRT = EXTRT,
    EXDOSE = as.numeric(EXDOSE),
    EXDOSU = EXDOSU,
    EXDOSFRM = EXDOSFRM,
    EXDOSFRQ = EXDOSFRQ,
    EXROUTE = EXROUTE,
    EXSTDTC = EXSTDTC,
    EXENDTC = EXENDTC
  ) %>%
  select(
    USUBJID, EXSEQ, EXTRT, EXDOSE, EXDOSU,
    EXDOSFRM, EXDOSFRQ, EXROUTE,
    EXSTDTC, EXENDTC
  )

# ---- Derive exposure duration and cumulative dose ----
cat("Deriving exposure metrics...\n")
adex_summary <- adex %>%
  group_by(USUBJID) %>%
  summarise(
    NEXP = n(),
    CUMDOSE = sum(EXDOSE, na.rm = TRUE),
    FIRST_EXSTDTC = min(EXSTDTC, na.rm = TRUE),
    LAST_EXENDTC = max(EXENDTC, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    EXDUR = as.numeric(
      as.Date(LAST_EXENDTC) - as.Date(FIRST_EXSTDTC) + 1
    )
  ) %>%
  select(USUBJID, NEXP, CUMDOSE, EXDUR)

# ---- Create exposure flag ----
cat("Creating exposure flag...\n")
adex_final <- adex %>%
  left_join(adex_summary, by = "USUBJID") %>%
  mutate(
    EXPOSFL = "Y"
  )

# ---- Add treatment variables ----
cat("Adding treatment variables...\n")
adex_final <- adex_final %>%
  left_join(
    adsl %>% select(USUBJID, TRT01P, TRT01PN, SAFFL),
    by = "USUBJID"
  ) %>%
  mutate(
    TRTP = TRT01P,
    TRTPN = TRT01PN
  ) %>%
  filter(SAFFL == "Y") %>%  # Keep only safety population
  select(-SAFFL)

# ---- Add labels ----
cat("Adding variable labels...\n")
attr(adex_final$USUBJID, "label") <- "Unique Subject Identifier"
attr(adex_final$EXSEQ, "label") <- "Sequence Number"
attr(adex_final$EXTRT, "label") <- "Name of Treatment"
attr(adex_final$EXDOSE, "label") <- "Dose per Administration"
attr(adex_final$EXDOSU, "label") <- "Dose Units"
attr(adex_final$EXDOSFRM, "label") <- "Dose Form"
attr(adex_final$EXDOSFRQ, "label") <- "Dosing Frequency per Interval"
attr(adex_final$EXROUTE, "label") <- "Route of Administration"
attr(adex_final$EXSTDTC, "label") <- "Start Date/Time of Treatment"
attr(adex_final$EXENDTC, "label") <- "End Date/Time of Treatment"
attr(adex_final$EXDUR, "label") <- "Duration of Exposure"
attr(adex_final$CUMDOSE, "label") <- "Cumulative Dose"
attr(adex_final$NEXP, "label") <- "Number of Exposures"
attr(adex_final$EXPOSFL, "label") <- "Exposure Flag"
attr(adex_final$TRTP, "label") <- "Planned Treatment"
attr(adex_final$TRTPN, "label") <- "Planned Treatment (N)"

# ---- Export ----
cat("Exporting ADEX dataset...\n")
output_dir <- "/workspace/data"
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# Export to Dataset-JSON
tryCatch({
  datasetjson::write_dataset_json(\1, file.path(output_dir, "\2"))
  cat("Exported to Dataset-JSON format.\\n")
}, error = function(e) {
  cat("Dataset-JSON export failed:", e$message, "\\n")
  cat("Saving as RDS only.\\n")
})
saveRDS(\1, file.path(output_dir, "\3"))
cat("Saved as RDS format.\\n")

cat("ADEX generation complete. Records:", nrow(adex_final), "\n")
cat("Output saved to:", file.path(output_dir, "adex.json"), "\n")