# Name: 05_adae.R
# Description: Generate ADAE (Adverse Events Analysis Dataset)
# Source SDTM: AE, SUPPAE, ADSL
# Supports TLGs: T-18, T-19, L-03, L-04, L-05, L-06
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

source("/private/var/folders/k_/kns3xnh95lsc57yvx3rhxj100000gn/T/mediforce-local-workspace-hB8wZb/code/00_setup.R")

# ---- Read source data ----
ae     <- read_sdtm("ae")
suppae <- read_sdtm("suppae")
adsl   <- readRDS(file.path(ADAM_DIR, "adsl.rds"))

# ---- Merge SUPPAE (AETRTEM flag) ----
suppae_wide <- suppae %>%
  filter(QNAM == "AETRTEM") %>%
  select(USUBJID, AESEQ = IDVARVAL, TRTEMFL = QVAL) %>%
  mutate(AESEQ = as.numeric(AESEQ))

ae_merged <- ae %>%
  left_join(suppae_wide, by = c("USUBJID", "AESEQ")) %>%
  mutate(
    TRTEMFL = coalesce(TRTEMFL, "N")
  )

# ---- Join with ADSL ----
adsl_sub <- adsl %>%
  select(USUBJID, STUDYID, TRT01A, TRT01AN, SAFFL, ITTFL, TRTSDT, TRTEDT, SITEID, AGE, SEX, RACE, ARMCD)

adae <- ae_merged %>%
  left_join(adsl_sub, by = "USUBJID") %>%
  filter(SAFFL == "Y") %>%
  mutate(
    # Date derivations
    ASTDT  = as.Date(substr(AESTDTC, 1, 10)),
    AENDT  = as.Date(substr(AEENDTC, 1, 10)),
    ASTDY  = AESTDY,
    AENDY  = AEENDY,

    # Treatment-emergent: start date >= treatment start date (or after)
    # Also use the SUPPAE AETRTEM flag
    TRTEMFL = if_else(
      is.na(ASTDT) | is.na(TRTSDT),
      TRTEMFL,
      if_else(ASTDT >= TRTSDT, "Y", "N")
    ),

    # Serious AE flag
    AESERF  = if_else(AESER == "Y", "Y", "N"),

    # Fatal outcome flag
    AESDTHFL = if_else(!is.na(AESDTH) & AESDTH == "Y", "Y", "N"),

    # Severity numeric
    AESEVN = case_when(
      AESEV == "MILD"     ~ 1L,
      AESEV == "MODERATE" ~ 2L,
      AESEV == "SEVERE"   ~ 3L,
      TRUE ~ NA_integer_
    ),

    # Action taken with study drug numeric
    AEACNN = case_when(
      AEACN == "DOSE NOT CHANGED"   ~ 1L,
      AEACN == "DOSE REDUCED"       ~ 2L,
      AEACN == "DRUG INTERRUPTED"   ~ 3L,
      AEACN == "DRUG WITHDRAWN"     ~ 4L,
      AEACN == "NOT APPLICABLE"     ~ 5L,
      TRUE ~ NA_integer_
    ),

    # MedDRA hierarchy variables (already in SDTM)
    AEBODSYS = AEBODSYS,
    AEDECOD  = AEDECOD,
    AETERM   = AETERM,
    AESOC    = AESOC,
    AELLT    = AELLT,

    # Dermatological events (for ADTTE)
    DERM_FL  = if_else(
      AESOC == "SKIN AND SUBCUTANEOUS TISSUE DISORDERS" |
        AEBODSYS == "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",
      "Y", "N"
    ),

    DOMAIN   = "ADAE",
    STUDYID_ADM = "CDISCPILOT01"
  ) %>%
  select(
    STUDYID_ADM, USUBJID, DOMAIN, AESEQ,
    AETERM, AELLT, AELLTCD, AEDECOD, AEPTCD,
    AEHLT, AEHLTCD, AEHLGT, AEHLGTCD,
    AEBODSYS, AEBDSYCD, AESOC, AESOCCD,
    ASTDT, ASTDY, AENDT, AENDY,
    AESEV, AESEVN, AESER, AESERF, AEACN, AEACNN,
    AEREL, AEOUT,
    AESCONG, AESDISAB, AESDTH, AESDTHFL,
    AESHOSP, AESLIFE, AESOD,
    TRTEMFL, DERM_FL,
    TRT01A, TRT01AN, SAFFL, ITTFL,
    SITEID, AGE, SEX, RACE, ARMCD,
    TRTSDT, TRTEDT
  ) %>%
  rename(STUDYID = STUDYID_ADM) %>%
  select(STUDYID, everything()) %>%
  arrange(USUBJID, AESEQ)

# ---- Validate ----
cat("ADAE rows:", nrow(adae), "\n")
cat("Subjects:", n_distinct(adae$USUBJID), "\n")
cat("TRTEMFL:\n")
print(table(adae$TRTEMFL))
cat("Serious AEs:", sum(adae$AESERF == "Y", na.rm = TRUE), "\n")
cat("Dermatological TEAEs:", sum(adae$TRTEMFL == "Y" & adae$DERM_FL == "Y", na.rm = TRUE), "\n")
cat("TEAEs by arm:\n")
print(table(adae$TRT01A[adae$TRTEMFL == "Y"]))

# ---- Export ----
write_adam(adae, "adae")
saveRDS(adae, file.path(ADAM_DIR, "adae.rds"))
