# Name: 05_adeff.R
# Description: Generate ADEFF dataset for CDISCPILOT01
# Source SDTM: QS, ADSL
# Supports TLGs: T-14.2.1 through T-14.2.9, F-15.1.1 through F-15.1.3, L-16.2.1
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

# ---- Setup ----
library(admiral)
library(dplyr)
library(lubridate)
library(stringr)
library(tidyr)

# Source helper functions
source("/workspace/code/00_setup.R")

# ---- Read source data ----
cat("Reading source data...\n")
qs <- read_sdtm("QS")
adsl <- readRDS("/workspace/data/adsl.rds")

# ---- Prepare QS data ----
cat("Preparing QS data...\n")
qsprep <- qs %>%
  filter(
    QSTESTCD %in% c("ADAS11", "CIBIC+", "NPI-X", "MMSE"),
    !is.na(QSSTRESN)
  ) %>%
  mutate(
    PARAMCD = case_when(
      QSTESTCD == "ADAS11" ~ "ADAS11",
      QSTESTCD == "CIBIC+" ~ "CIBIC",
      QSTESTCD == "NPI-X" ~ "NPIX",
      QSTESTCD == "MMSE" ~ "MMSE",
      TRUE ~ QSTESTCD
    ),
    PARAM = case_when(
      QSTESTCD == "ADAS11" ~ "ADAS-Cog (11) Total Score",
      QSTESTCD == "CIBIC+" ~ "CIBIC+ Score",
      QSTESTCD == "NPI-X" ~ "Neuropsychiatric Inventory Total Score",
      QSTESTCD == "MMSE" ~ "Mini-Mental State Examination Score",
      TRUE ~ QSTEST
    ),
    AVISITN = VISITNUM,
    AVISIT = case_when(
      VISITNUM == 1 ~ "Screening",
      VISITNUM == 3 ~ "Baseline",
      VISITNUM == 4 ~ "Week 4",
      VISITNUM == 5 ~ "Week 8",
      VISITNUM == 7 ~ "Week 12",
      VISITNUM == 8 ~ "Week 16",
      VISITNUM == 9 ~ "Week 20",
      VISITNUM == 10 ~ "Week 24",
      VISITNUM == 11 ~ "Week 26",
      TRUE ~ VISIT
    ),
    ADT = as.Date(QSDTC),
    AVAL = QSSTRESN
  ) %>%
  select(USUBJID, PARAMCD, PARAM, AVISITN, AVISIT, ADT, AVAL)

# ---- Add study day relative to RFSTDTC ----
cat("Adding study day...\n")
qsprep <- qsprep %>%
  left_join(
    adsl %>% select(USUBJID, RFSTDTC),
    by = "USUBJID"
  ) %>%
  mutate(
    RFSTDT = as.Date(RFSTDTC),
    ADY = as.numeric(ADT - RFSTDT)
  ) %>%
  select(-RFSTDTC, -RFSTDT)

# ---- Derive baseline values ----
cat("Deriving baseline values...\n")
base <- qsprep %>%
  filter(AVISIT == "Baseline") %>%
  select(USUBJID, PARAMCD, BASE = AVAL)

# ---- Create ADEFF structure ----
cat("Creating ADEFF structure...\n")
adeff <- qsprep %>%
  left_join(base, by = c("USUBJID", "PARAMCD")) %>%
  mutate(
    CHG = ifelse(AVISIT != "Baseline", AVAL - BASE, NA_real_),
    PCHG = ifelse(AVISIT != "Baseline" & BASE != 0, (CHG / BASE) * 100, NA_real_),
    ABLFL = ifelse(AVISIT == "Baseline", "Y", NA_character_)
  )

# ---- LOCF imputation ----
cat("Applying LOCF imputation...\n")
# Get expected visits for each parameter
expected_visits <- c("Baseline", "Week 4", "Week 8", "Week 12", "Week 16", "Week 20", "Week 24")

# Create complete grid of subjects x parameters x visits
subj_params <- adeff %>%
  distinct(USUBJID, PARAMCD)

visit_grid <- expand_grid(
  USUBJID = unique(adeff$USUBJID),
  PARAMCD = unique(adeff$PARAMCD),
  AVISIT = expected_visits
) %>%
  mutate(
    AVISITN = case_when(
      AVISIT == "Baseline" ~ 3,
      AVISIT == "Week 4" ~ 4,
      AVISIT == "Week 8" ~ 5,
      AVISIT == "Week 12" ~ 7,
      AVISIT == "Week 16" ~ 8,
      AVISIT == "Week 20" ~ 9,
      AVISIT == "Week 24" ~ 10
    )
  )

# Merge with actual data and carry forward
adeff_locf <- visit_grid %>%
  left_join(
    adeff %>% select(USUBJID, PARAMCD, AVISIT, AVAL, BASE, CHG, PCHG, ABLFL, ADT, ADY),
    by = c("USUBJID", "PARAMCD", "AVISIT")
  ) %>%
  group_by(USUBJID, PARAMCD) %>%
  arrange(AVISITN) %>%
  fill(AVAL, .direction = "down") %>%
  fill(BASE, .direction = "down") %>%
  mutate(
    CHG = ifelse(AVISIT != "Baseline", AVAL - BASE, NA_real_),
    PCHG = ifelse(AVISIT != "Baseline" & BASE != 0, (CHG / BASE) * 100, NA_real_),
    ABLFL = ifelse(AVISIT == "Baseline", "Y", NA_character_),
    LOCFFL = ifelse(is.na(AVAL) & !is.na(lag(AVAL)), "Y", NA_character_)
  ) %>%
  ungroup()

# ---- Add treatment and demographic variables ----
cat("Adding treatment and demographic variables...\n")
adeff_final <- adeff_locf %>%
  left_join(
    adsl %>% select(
      USUBJID, TRT01P, TRT01PN, SEX, AGE, AGEGR1, RACE, ETHNIC,
      MMSEBL, ADASCOGBL, CIBICBL, DISDURBL, EFFFL
    ),
    by = "USUBJID"
  ) %>%
  mutate(
    TRTP = TRT01P,
    TRTPN = TRT01PN,
    EFFFL = ifelse(is.na(EFFFL), "N", EFFFL)
  ) %>%
  filter(EFFFL == "Y") %>%  # Keep only efficacy population
  select(-EFFFL)

# ---- Add labels ----
cat("Adding variable labels...\n")
attr(adeff_final$USUBJID, "label") <- "Unique Subject Identifier"
attr(adeff_final$PARAMCD, "label") <- "Parameter Code"
attr(adeff_final$PARAM, "label") <- "Parameter"
attr(adeff_final$AVISITN, "label") <- "Analysis Visit (N)"
attr(adeff_final$AVISIT, "label") <- "Analysis Visit"
attr(adeff_final$ADT, "label") <- "Analysis Date"
attr(adeff_final$ADY, "label") <- "Analysis Relative Day"
attr(adeff_final$AVAL, "label") <- "Analysis Value"
attr(adeff_final$BASE, "label") <- "Baseline Value"
attr(adeff_final$CHG, "label") <- "Change from Baseline"
attr(adeff_final$PCHG, "label") <- "Percent Change from Baseline"
attr(adeff_final$ABLFL, "label") <- "Baseline Record Flag"
attr(adeff_final$LOCFFL, "label") <- "Last Observation Carried Forward Flag"
attr(adeff_final$TRTP, "label") <- "Planned Treatment"
attr(adeff_final$TRTPN, "label") <- "Planned Treatment (N)"
attr(adeff_final$SEX, "label") <- "Sex"
attr(adeff_final$AGE, "label") <- "Age"
attr(adeff_final$AGEGR1, "label") <- "Age Group"
attr(adeff_final$RACE, "label") <- "Race"
attr(adeff_final$ETHNIC, "label") <- "Ethnicity"
attr(adeff_final$MMSEBL, "label") <- "Baseline MMSE Score"
attr(adeff_final$ADASCOGBL, "label") <- "Baseline ADAS-Cog (11) Score"
attr(adeff_final$CIBICBL, "label") <- "Baseline CIBIC+ Score"
attr(adeff_final$DISDURBL, "label") <- "Disease Duration at Baseline (years)"

# ---- Export ----
cat("Exporting ADEFF dataset...\n")
output_dir <- "/workspace/data"
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# Export to Dataset-JSON
tryCatch({
  datasetjson::write_dataset_json(\1, file.path(output_dir, "\2"))
  cat("Exported to Dataset-JSON format.\\n")
}, error = function(e) {
  cat("Dataset-JSON export failed:", e$message, "\\n")
  cat("Saving as RDS only.\\n")
})
saveRDS(\1, file.path(output_dir, "\3"))
cat("Saved as RDS format.\\n")

cat("ADEFF generation complete. Records:", nrow(adeff_final), "\n")
cat("Parameters:", paste(unique(adeff_final$PARAMCD), collapse = ", "), "\n")
cat("Output saved to:", file.path(output_dir, "adeff.json"), "\n")