# Name: 06_adlb.R
# Description: Generate ADLB (Laboratory Data Analysis Dataset)
# Source SDTM: LB, SUPPLB, ADSL
# Supports TLGs: T-20, T-21, T-22, T-23, T-24, T-25
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

source("/private/var/folders/k_/kns3xnh95lsc57yvx3rhxj100000gn/T/mediforce-local-workspace-hB8wZb/code/00_setup.R")

# ---- Read source data ----
lb     <- read_sdtm("lb")
supplb <- read_sdtm("supplb")
adsl   <- readRDS(file.path(ADAM_DIR, "adsl.rds"))

# ---- Merge SUPPLB ----
# SUPPLB has LBTMSHI (Hy's Law shift indicator) and ENDPOINT
supplb_wide <- supplb %>%
  select(USUBJID, IDVAR, IDVARVAL, QNAM, QVAL) %>%
  pivot_wider(names_from = QNAM, values_from = QVAL) %>%
  rename(LBSEQ = IDVARVAL) %>%
  mutate(LBSEQ = as.numeric(LBSEQ))

lb_merged <- lb %>%
  left_join(supplb_wide %>% select(-IDVAR), by = c("USUBJID", "LBSEQ"))

# ---- Join with ADSL ----
adsl_sub <- adsl %>%
  select(USUBJID, STUDYID, TRT01A, TRT01AN, SAFFL, ITTFL, TRTSDT, TRTEDT,
         SITEID, AGE, SEX, RACE, ARMCD)

# ---- Build ADLB ----
adlb_raw <- lb_merged %>%
  left_join(adsl_sub, by = "USUBJID") %>%
  filter(SAFFL == "Y") %>%
  mutate(
    # Date handling
    ADT     = as.Date(substr(LBDTC, 1, 10)),
    ADY     = LBDY,
    VISITNUM_N = as.numeric(VISITNUM),

    # Visit assignment
    AVISIT = case_when(
      VISIT == "SCREENING 1"  ~ "Baseline",
      VISIT == "WEEK 2"       ~ "Week 2",
      VISIT == "WEEK 4"       ~ "Week 4",
      VISIT == "WEEK 6"       ~ "Week 6",
      VISIT == "WEEK 8"       ~ "Week 8",
      VISIT == "WEEK 12"      ~ "Week 12",
      VISIT == "WEEK 16"      ~ "Week 16",
      VISIT == "WEEK 20"      ~ "Week 20",
      VISIT == "WEEK 24"      ~ "Week 24",
      VISIT == "WEEK 26"      ~ "Week 26",
      VISIT == "RETRIEVAL"    ~ "End of Treatment",
      TRUE ~ VISIT
    ),
    AVISITN = case_when(
      AVISIT == "Baseline"         ~ 0L,
      AVISIT == "Week 2"           ~ 2L,
      AVISIT == "Week 4"           ~ 4L,
      AVISIT == "Week 6"           ~ 6L,
      AVISIT == "Week 8"           ~ 8L,
      AVISIT == "Week 12"          ~ 12L,
      AVISIT == "Week 16"          ~ 16L,
      AVISIT == "Week 20"          ~ 20L,
      AVISIT == "Week 24"          ~ 24L,
      AVISIT == "Week 26"          ~ 26L,
      AVISIT == "End of Treatment" ~ 99L,
      TRUE ~ NA_integer_
    ),

    # Parameters
    PARAMCD = LBTESTCD,
    PARAM   = LBTEST,
    PARCAT1 = LBCAT,

    # Analysis values
    AVAL    = LBSTRESN,
    AVALC   = LBSTRESC,
    AVALU   = LBSTRESU,

    # Reference ranges
    ANRLO   = LBSTNRLO,
    ANRHI   = LBSTNRHI,

    # Normal range indicator
    ANRIND  = LBNRIND,

    # Shift category (L/N/H)
    SHIFT1  = case_when(
      LBNRIND == "LOW"    ~ "L",
      LBNRIND == "NORMAL" ~ "N",
      LBNRIND == "HIGH"   ~ "H",
      TRUE ~ NA_character_
    ),

    DOMAIN  = "ADLB",
    STUDYID = "CDISCPILOT01"
  ) %>%
  filter(!is.na(AVISITN))

# ---- Derive baseline values (Screening 1 = Visit 1) ----
# Per SAP: baseline for lab values = Week -2 (Visit 1 = SCREENING 1)
baseline_labs <- adlb_raw %>%
  filter(AVISIT == "Baseline") %>%
  group_by(USUBJID, PARAMCD) %>%
  arrange(ADT) %>%
  slice(1) %>%
  ungroup() %>%
  mutate(ABLFL = "Y") %>%
  select(USUBJID, PARAMCD, BASE = AVAL, BASEC = AVALC, BNRIND = ANRIND, SHIFT1BL = SHIFT1, ABLFL)

adlb <- adlb_raw %>%
  left_join(baseline_labs, by = c("USUBJID", "PARAMCD")) %>%
  mutate(
    # Baseline flag
    ABLFL = coalesce(ABLFL, NA_character_),

    # Change from baseline
    CHG   = if_else(!is.na(AVAL) & !is.na(BASE) & AVISITN > 0, AVAL - BASE, NA_real_),
    PCHG  = if_else(!is.na(CHG) & !is.na(BASE) & BASE != 0, CHG / BASE * 100, NA_real_),

    # Shift from baseline
    SHTBL1 = case_when(
      !is.na(BNRIND) & !is.na(ANRIND) ~ paste0(
        case_when(BNRIND == "LOW" ~ "L", BNRIND == "NORMAL" ~ "N", BNRIND == "HIGH" ~ "H", TRUE ~ "?"),
        "->",
        case_when(ANRIND == "LOW" ~ "L", ANRIND == "NORMAL" ~ "N", ANRIND == "HIGH" ~ "H", TRUE ~ "?")
      ),
      TRUE ~ NA_character_
    ),

    # Hy's Law flag (from SUPPLB)
    HTLMSHI = if (exists("LBTMSHI", where = as.list(.))) LBTMSHI else NA_character_,

    # Treatment-emergent abnormal (CRITFL)
    CRITFL = if_else(
      AVISITN > 0 & !is.na(ANRIND) & ANRIND %in% c("LOW", "HIGH", "ABNORMAL") &
        (is.na(BNRIND) | BNRIND == "NORMAL"),
      "Y", "N"
    )
  ) %>%
  select(
    STUDYID, USUBJID, DOMAIN, LBSEQ,
    PARAMCD, PARAM, PARCAT1,
    ADT, ADY, AVISIT, AVISITN,
    AVAL, AVALC, AVALU,
    BASE, BASEC, BNRIND,
    CHG, PCHG,
    ANRLO, ANRHI, ANRIND,
    ABLFL, SHIFT1, SHIFT1BL, SHTBL1, CRITFL,
    TRT01A, TRT01AN, SAFFL, ITTFL,
    SITEID, AGE, SEX, RACE, ARMCD,
    TRTSDT, TRTEDT
  ) %>%
  arrange(USUBJID, PARAMCD, AVISITN, ADT)

# Remove columns that don't exist
adlb <- adlb[, names(adlb)[names(adlb) %in% c(
  "STUDYID", "USUBJID", "DOMAIN", "LBSEQ",
  "PARAMCD", "PARAM", "PARCAT1",
  "ADT", "ADY", "AVISIT", "AVISITN",
  "AVAL", "AVALC", "AVALU",
  "BASE", "BASEC", "BNRIND",
  "CHG", "PCHG",
  "ANRLO", "ANRHI", "ANRIND",
  "ABLFL", "SHIFT1", "SHIFT1BL", "SHTBL1", "CRITFL",
  "TRT01A", "TRT01AN", "SAFFL", "ITTFL",
  "SITEID", "AGE", "SEX", "RACE", "ARMCD",
  "TRTSDT", "TRTEDT"
)]]

# ---- Validate ----
cat("ADLB rows:", nrow(adlb), "\n")
cat("Subjects:", n_distinct(adlb$USUBJID), "\n")
cat("Parameters:", n_distinct(adlb$PARAMCD), "\n")
cat("Visits:\n")
print(table(adlb$AVISIT))
cat("\nBNRIND counts:\n")
print(table(adlb$BNRIND, useNA = "ifany"))
cat("ANRIND counts:\n")
print(table(adlb$ANRIND, useNA = "ifany"))

# ---- Export ----
write_adam(adlb, "adlb")
saveRDS(adlb, file.path(ADAM_DIR, "adlb.rds"))
