# Name: 06_adae.R
# Description: Generate ADAE dataset for CDISCPILOT01
# Source SDTM: AE, EX, ADSL
# Supports TLGs: T-14.3.1.1 through T-14.3.1.6, L-16.3.1 through L-16.3.4, F-15.2.1 through F-15.2.2
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

# ---- Setup ----
library(admiral)
library(dplyr)
library(lubridate)
library(stringr)
library(tidyr)

# Source helper functions
source("/workspace/code/00_setup.R")

# ---- Read source data ----
cat("Reading source data...\n")
ae <- read_sdtm("AE")
ex <- read_sdtm("EX")
adsl <- readRDS("/workspace/data/adsl.rds")

# ---- Prepare AE data ----
cat("Preparing AE data...\n")
aeprep <- ae %>%
  mutate(
    AESEQ = as.numeric(AESEQ),
    AETERM = AETERM,
    AEDECOD = AEDECOD,
    AEBODSYS = AEBODSYS,
    AESER = AESER,
    AEREL = AEREL,
    AEOUT = AEOUT,
    AESEV = AESEV,
    AETOXGR = as.numeric(AETOXGR),
    AESTDTC = AESTDTC,
    AEENDTC = AEENDTC
  ) %>%
  select(
    USUBJID, AESEQ, AETERM, AEDECOD, AEBODSYS,
    AESER, AEREL, AEOUT, AESEV, AETOXGR,
    AESTDTC, AEENDTC
  )

# ---- Get first and last treatment dates ----
cat("Getting treatment dates...\n")
treatment_dates <- ex %>%
  group_by(USUBJID) %>%
  summarise(
    RFXSTDTC = min(EXSTDTC, na.rm = TRUE),
    RFXENDTC = max(EXENDTC, na.rm = TRUE),
    .groups = "drop"
  )

# ---- Derive treatment-emergent flag ----
cat("Deriving treatment-emergent flag...\n")
adae <- aeprep %>%
  left_join(treatment_dates, by = "USUBJID") %>%
  mutate(
    TRTEMFL = ifelse(
      !is.na(AESTDTC) & 
      AESTDTC >= RFXSTDTC &
      (is.na(RFXENDTC) | AESTDTC <= as.Date(RFXENDTC) + days(30)),
      "Y", "N"
    ),
    TRTRELFL = ifelse(AEREL %in% c("POSSIBLE", "PROBABLE", "DEFINITE"), "Y", "N"),
    SERFL = ifelse(AESER == "Y", "Y", "N"),
    WDRAWFL = ifelse(grepl("WITHDRAWAL", toupper(AEOUT)), "Y", "N"),
    DSCHFL = ifelse(grepl("DISCONTINUATION", toupper(AEOUT)), "Y", "N"),
    DEATHFL = ifelse(grepl("DEATH", toupper(AEOUT)), "Y", "N")
  )

# ---- Derive study days and duration ----
cat("Deriving study days and duration...\n")
adae <- adae %>%
  left_join(
    adsl %>% select(USUBJID, RFSTDTC),
    by = "USUBJID"
  ) %>%
  mutate(
    RFSTDT = as.Date(RFSTDTC),
    AESTDT = as.Date(AESTDTC),
    AEENDT = as.Date(AEENDTC),
    AESTDY = as.numeric(AESTDT - RFSTDT),
    AEENDY = as.numeric(AEENDT - RFSTDT),
    AEDUR = ifelse(!is.na(AESTDT) & !is.na(AEENDT), 
                   as.numeric(AEENDT - AESTDT) + 1, NA_real_)
  ) %>%
  select(-RFSTDTC, -RFSTDT, -AESTDT, -AEENDT)

# ---- Add treatment variables ----
cat("Adding treatment variables...\n")
adae_final <- adae %>%
  left_join(
    adsl %>% select(USUBJID, TRT01P, TRT01PN, SAFFL),
    by = "USUBJID"
  ) %>%
  mutate(
    TRTP = TRT01P,
    TRTPN = TRT01PN
  ) %>%
  filter(SAFFL == "Y") %>%  # Keep only safety population
  select(-SAFFL)

# ---- Add labels ----
cat("Adding variable labels...\n")
attr(adae_final$USUBJID, "label") <- "Unique Subject Identifier"
attr(adae_final$AESEQ, "label") <- "Sequence Number"
attr(adae_final$AETERM, "label") <- "Reported Term for the Adverse Event"
attr(adae_final$AEDECOD, "label") <- "Dictionary-Derived Term"
attr(adae_final$AEBODSYS, "label") <- "Body System or Organ Class"
attr(adae_final$AESER, "label") <- "Serious Event"
attr(adae_final$AEREL, "label") <- "Causality"
attr(adae_final$AEOUT, "label") <- "Outcome of Adverse Event"
attr(adae_final$AESEV, "label") <- "Severity/Intensity"
attr(adae_final$AETOXGR, "label") <- "Standard Toxicity Grade"
attr(adae_final$AESTDTC, "label") <- "Start Date/Time of Adverse Event"
attr(adae_final$AEENDTC, "label") <- "End Date/Time of Adverse Event"
attr(adae_final$TRTEMFL, "label") <- "Treatment Emergent Flag"
attr(adae_final$TRTRELFL, "label") <- "Treatment Related Flag"
attr(adae_final$SERFL, "label") <- "Serious Flag"
attr(adae_final$WDRAWFL, "label") <- "Led to Withdrawal Flag"
attr(adae_final$DSCHFL, "label") <- "Led to Discontinuation Flag"
attr(adae_final$DEATHFL, "label") <- "Resulted in Death Flag"
attr(adae_final$AESTDY, "label") <- "Study Day of Start of Adverse Event"
attr(adae_final$AEENDY, "label") <- "Study Day of End of Adverse Event"
attr(adae_final$AEDUR, "label") <- "Duration of Adverse Event"
attr(adae_final$TRTP, "label") <- "Planned Treatment"
attr(adae_final$TRTPN, "label") <- "Planned Treatment (N)"

# ---- Export ----
cat("Exporting ADAE dataset...\n")
output_dir <- "/workspace/data"
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# Export to Dataset-JSON
tryCatch({
  datasetjson::write_dataset_json(\1, file.path(output_dir, "\2"))
  cat("Exported to Dataset-JSON format.\\n")
}, error = function(e) {
  cat("Dataset-JSON export failed:", e$message, "\\n")
  cat("Saving as RDS only.\\n")
})
saveRDS(\1, file.path(output_dir, "\3"))
cat("Saved as RDS format.\\n")

cat("ADAE generation complete. Records:", nrow(adae_final), "\n")
cat("Subjects with AEs:", n_distinct(adae_final$USUBJID), "\n")
cat("Output saved to:", file.path(output_dir, "adae.json"), "\n")