# Name: 07_adlb.R
# Description: Generate ADLB dataset for CDISCPILOT01
# Source SDTM: LB, ADSL
# Supports TLGs: T-14.3.2.1, T-14.3.2.2, L-16.3.5
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

# ---- Setup ----
library(admiral)
library(dplyr)
library(lubridate)
library(stringr)
library(tidyr)

# Source helper functions
source("/workspace/code/00_setup.R")

# ---- Read source data ----
cat("Reading source data...\n")
lb <- read_sdtm("LB")
adsl <- readRDS("/workspace/data/adsl.rds")

# ---- Prepare LB data ----
cat("Preparing LB data...\n")
lbprep <- lb %>%
  filter(!is.na(LBSTRESN)) %>%
  mutate(
    LBSEQ = as.numeric(LBSEQ),
    LBTESTCD = LBTESTCD,
    LBTEST = LBTEST,
    LBCAT = LBCAT,
    LBSCAT = LBSCAT,
    LBORRES = LBORRES,
    LBORRESU = LBORRESU,
    LBSTRESC = LBSTRESC,
    LBSTRESN = as.numeric(LBSTRESN),
    LBSTRESU = LBSTRESU,
    LBNRIND = LBNRIND,
    LBLLN = as.numeric(LBLLN),
    LBULN = as.numeric(LBULN),
    LBDTC = LBDTC,
    VISITNUM = VISITNUM,
    VISIT = VISIT,
    AVAL = LBSTRESN,
    BASE = NA_real_,  # Will be filled later
    A1LO = LBLLN,
    A1HI = LBULN,
    ANRLO = LBLLN,
    ANRHI = LBULN
  ) %>%
  select(
    USUBJID, LBSEQ, LBTESTCD, LBTEST, LBCAT, LBSCAT,
    LBORRES, LBORRESU, LBSTRESC, LBSTRESN, LBSTRESU,
    LBNRIND, LBLLN, LBULN, LBDTC, VISITNUM, VISIT,
    AVAL, BASE, A1LO, A1HI, ANRLO, ANRHI
  )

# ---- Derive baseline values ----
cat("Deriving baseline values...\n")
base_lb <- lbprep %>%
  filter(VISITNUM == 3) %>%  # Baseline visit
  group_by(USUBJID, LBTESTCD) %>%
  arrange(LBDTC) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  select(USUBJID, LBTESTCD, BASE = AVAL, BASERIND = LBNRIND)

# ---- Create ADLB structure ----
cat("Creating ADLB structure...\n")
adlb <- lbprep %>%
  left_join(base_lb, by = c("USUBJID", "LBTESTCD")) %>%
  mutate(
    CHG = ifelse(VISITNUM != 3, AVAL - BASE, NA_real_),
    ANRIND = case_when(
      !is.na(A1LO) & !is.na(A1HI) & AVAL < A1LO ~ "LOW",
      !is.na(A1LO) & !is.na(A1HI) & AVAL > A1HI ~ "HIGH",
      !is.na(A1LO) & !is.na(A1HI) & AVAL >= A1LO & AVAL <= A1HI ~ "NORMAL",
      TRUE ~ NA_character_
    ),
    SHIFT1 = ifelse(
      !is.na(BASERIND) & !is.na(ANRIND),
      paste(BASERIND, "->", ANRIND),
      NA_character_
    )
  )

# ---- Add treatment variables ----
cat("Adding treatment variables...\n")
adlb_final <- adlb %>%
  left_join(
    adsl %>% select(USUBJID, TRT01P, TRT01PN, SAFFL),
    by = "USUBJID"
  ) %>%
  mutate(
    TRTP = TRT01P,
    TRTPN = TRT01PN
  ) %>%
  filter(SAFFL == "Y") %>%  # Keep only safety population
  select(-SAFFL)

# ---- Add labels ----
cat("Adding variable labels...\n")
attr(adlb_final$USUBJID, "label") <- "Unique Subject Identifier"
attr(adlb_final$LBSEQ, "label") <- "Sequence Number"
attr(adlb_final$LBTESTCD, "label") <- "Lab Test or Examination Short Name"
attr(adlb_final$LBTEST, "label") <- "Lab Test or Examination Name"
attr(adlb_final$LBCAT, "label") <- "Category for Lab Test"
attr(adlb_final$LBSCAT, "label") <- "Subcategory for Lab Test"
attr(adlb_final$LBORRES, "label") <- "Result or Finding in Original Units"
attr(adlb_final$LBORRESU, "label") <- "Original Units"
attr(adlb_final$LBSTRESC, "label") <- "Character Result/Finding in Std Format"
attr(adlb_final$LBSTRESN, "label") <- "Numeric Result/Finding in Standard Units"
attr(adlb_final$LBSTRESU, "label") <- "Standard Units"
attr(adlb_final$LBNRIND, "label") <- "Reference Range Indicator"
attr(adlb_final$LBLLN, "label") <- "Lower Limit of Normal Range"
attr(adlb_final$LBULN, "label") <- "Upper Limit of Normal Range"
attr(adlb_final$LBDTC, "label") <- "Date/Time of Specimen Collection"
attr(adlb_final$VISITNUM, "label") <- "Visit Number"
attr(adlb_final$VISIT, "label") <- "Visit Name"
attr(adlb_final$AVAL, "label") <- "Analysis Value"
attr(adlb_final$BASE, "label") <- "Baseline Value"
attr(adlb_final$CHG, "label") <- "Change from Baseline"
attr(adlb_final$A1LO, "label") <- "Analysis Range Low Value"
attr(adlb_final$A1HI, "label") <- "Analysis Range High Value"
attr(adlb_final$ANRIND, "label") <- "Analysis Reference Range Indicator"
attr(adlb_final$ANRLO, "label") <- "Analysis Normal Range Lower Limit"
attr(adlb_final$ANRHI, "label") <- "Analysis Normal Range Upper Limit"
attr(adlb_final$SHIFT1, "label") <- "Shift from Baseline Category 1"
attr(adlb_final$TRTP, "label") <- "Planned Treatment"
attr(adlb_final$TRTPN, "label") <- "Planned Treatment (N)"

# ---- Export ----
cat("Exporting ADLB dataset...\n")
output_dir <- "/workspace/data"
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# Export to Dataset-JSON
tryCatch({
  datasetjson::write_dataset_json(\1, file.path(output_dir, "\2"))
  cat("Exported to Dataset-JSON format.\\n")
}, error = function(e) {
  cat("Dataset-JSON export failed:", e$message, "\\n")
  cat("Saving as RDS only.\\n")
})
saveRDS(\1, file.path(output_dir, "\3"))
cat("Saved as RDS format.\\n")

cat("ADLB generation complete. Records:", nrow(adlb_final), "\n")
cat("Lab tests:", n_distinct(adlb_final$LBTESTCD), "\n")
cat("Output saved to:", file.path(output_dir, "adlb.json"), "\n")