# Name: 07_advs.R
# Description: Generate ADVS (Vital Signs Analysis Dataset)
# Source SDTM: VS, ADSL
# Supports TLGs: T-26, T-27, T-28
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

source("/private/var/folders/k_/kns3xnh95lsc57yvx3rhxj100000gn/T/mediforce-local-workspace-hB8wZb/code/00_setup.R")

# ---- Read source data ----
vs   <- read_sdtm("vs")
adsl <- readRDS(file.path(ADAM_DIR, "adsl.rds"))

# ---- Join with ADSL ----
adsl_sub <- adsl %>%
  select(USUBJID, STUDYID, TRT01A, TRT01AN, SAFFL, ITTFL, TRTSDT, TRTEDT,
         SITEID, AGE, SEX, RACE, ARMCD)

# ---- Map VSTESTCD and VSPOS to parameter code ----
advs_raw <- vs %>%
  left_join(adsl_sub, by = "USUBJID") %>%
  filter(SAFFL == "Y") %>%
  mutate(
    # Date
    ADT     = as.Date(substr(VSDTC, 1, 10)),
    ADY     = VSDY,

    # Position-specific parameter codes
    PARAMCD = case_when(
      VSTESTCD == "SYSBP"  & (is.na(VSPOS) | VSPOS == "" | VSPOS == "SUPINE")   ~ "SYSBP",
      VSTESTCD == "SYSBP"  & VSPOS == "STANDING"                                  ~ "VSSBPST",
      VSTESTCD == "DIABP"  & (is.na(VSPOS) | VSPOS == "" | VSPOS == "SUPINE")   ~ "DIABP",
      VSTESTCD == "DIABP"  & VSPOS == "STANDING"                                  ~ "VSDBPST",
      VSTESTCD == "PULSE"  & (is.na(VSPOS) | VSPOS == "" | VSPOS == "SUPINE")   ~ "PULSE",
      VSTESTCD == "PULSE"  & VSPOS == "STANDING"                                  ~ "VSPULST",
      VSTESTCD == "WEIGHT"                                                          ~ "WEIGHT",
      VSTESTCD == "HEIGHT"                                                          ~ "HEIGHT",
      VSTESTCD == "TEMP"                                                            ~ "TEMP",
      TRUE ~ VSTESTCD
    ),
    PARAM = case_when(
      PARAMCD == "SYSBP"   ~ "Systolic Blood Pressure (Supine) (mmHg)",
      PARAMCD == "VSSBPST" ~ "Systolic Blood Pressure (Standing) (mmHg)",
      PARAMCD == "DIABP"   ~ "Diastolic Blood Pressure (Supine) (mmHg)",
      PARAMCD == "VSDBPST" ~ "Diastolic Blood Pressure (Standing) (mmHg)",
      PARAMCD == "PULSE"   ~ "Pulse Rate (Supine) (beats/min)",
      PARAMCD == "VSPULST" ~ "Pulse Rate (Standing) (beats/min)",
      PARAMCD == "WEIGHT"  ~ "Weight (kg)",
      PARAMCD == "HEIGHT"  ~ "Height (cm)",
      PARAMCD == "TEMP"    ~ "Temperature (C)",
      TRUE ~ VSTEST
    ),
    PARAMN = case_when(
      PARAMCD == "SYSBP"   ~ 1L,
      PARAMCD == "VSSBPST" ~ 2L,
      PARAMCD == "DIABP"   ~ 3L,
      PARAMCD == "VSDBPST" ~ 4L,
      PARAMCD == "PULSE"   ~ 5L,
      PARAMCD == "VSPULST" ~ 6L,
      PARAMCD == "WEIGHT"  ~ 7L,
      PARAMCD == "HEIGHT"  ~ 8L,
      PARAMCD == "TEMP"    ~ 9L,
      TRUE ~ NA_integer_
    ),

    # Visit assignment
    AVISIT = case_when(
      VISIT == "SCREENING 1"                 ~ "Screening",
      VISIT == "BASELINE"                    ~ "Baseline",
      VISIT == "WEEK 2"                      ~ "Week 2",
      VISIT == "WEEK 4"                      ~ "Week 4",
      VISIT == "WEEK 6"                      ~ "Week 6",
      VISIT == "WEEK 8"                      ~ "Week 8",
      VISIT == "WEEK 12"                     ~ "Week 12",
      VISIT == "WEEK 16"                     ~ "Week 16",
      VISIT == "WEEK 20"                     ~ "Week 20",
      VISIT %in% c("WEEK 24", "RETRIEVAL")  ~ "Week 24",
      VISIT == "WEEK 26"                     ~ "Week 26",
      TRUE ~ VISIT
    ),
    AVISITN = case_when(
      AVISIT == "Screening"       ~ -2L,
      AVISIT == "Baseline"        ~ 0L,
      AVISIT == "Week 2"          ~ 2L,
      AVISIT == "Week 4"          ~ 4L,
      AVISIT == "Week 6"          ~ 6L,
      AVISIT == "Week 8"          ~ 8L,
      AVISIT == "Week 12"         ~ 12L,
      AVISIT == "Week 16"         ~ 16L,
      AVISIT == "Week 20"         ~ 20L,
      AVISIT == "Week 24"         ~ 24L,
      AVISIT == "Week 26"         ~ 26L,
      TRUE ~ NA_integer_
    ),

    AVAL   = VSSTRESN,
    AVALU  = VSSTRESU,
    DOMAIN = "ADVS",
    STUDYID = "CDISCPILOT01"
  ) %>%
  filter(!is.na(AVISITN), !is.na(PARAMCD))

# ---- Select one record per subject per parameter per visit ----
advs_sel <- advs_raw %>%
  group_by(USUBJID, PARAMCD, AVISITN) %>%
  arrange(ADT) %>%
  slice(1) %>%
  ungroup()

# ---- Derive baseline ----
# Weight/BMI: Baseline = Visit 3 (BASELINE)
# Height: first available (Screening or Baseline)
# Other VS: Baseline = BASELINE visit

baseline_advs <- advs_sel %>%
  filter(
    (PARAMCD %in% c("SYSBP", "VSSBPST", "DIABP", "VSDBPST", "PULSE", "VSPULST", "TEMP") & AVISIT == "Baseline") |
    (PARAMCD == "WEIGHT" & AVISIT == "Baseline") |
    (PARAMCD == "HEIGHT" & AVISITN <= 0)
  ) %>%
  group_by(USUBJID, PARAMCD) %>%
  arrange(ADT) %>%
  slice(1) %>%
  ungroup() %>%
  mutate(ABLFL = "Y") %>%
  select(USUBJID, PARAMCD, BASE = AVAL, ABLFL)

advs <- advs_sel %>%
  left_join(baseline_advs, by = c("USUBJID", "PARAMCD")) %>%
  mutate(
    ABLFL = coalesce(ABLFL, NA_character_),
    CHG   = if_else(!is.na(AVAL) & !is.na(BASE) & AVISITN > 0, AVAL - BASE, NA_real_),
    PCHG  = if_else(!is.na(CHG) & !is.na(BASE) & BASE != 0, CHG / BASE * 100, NA_real_)
  ) %>%
  select(
    STUDYID, USUBJID, DOMAIN,
    PARAMCD, PARAM, PARAMN,
    ADT, ADY, AVISIT, AVISITN,
    AVAL, AVALU, BASE, CHG, PCHG,
    ABLFL,
    TRT01A, TRT01AN, SAFFL, ITTFL,
    SITEID, AGE, SEX, RACE, ARMCD,
    TRTSDT, TRTEDT
  ) %>%
  arrange(USUBJID, PARAMN, AVISITN)

# ---- Validate ----
cat("ADVS rows:", nrow(advs), "\n")
cat("Subjects:", n_distinct(advs$USUBJID), "\n")
cat("Parameters:\n")
print(table(advs$PARAMCD))
cat("\nWeight at Baseline:\n")
wt_bl <- advs[advs$PARAMCD == "WEIGHT" & advs$AVISIT == "Baseline",]
print(summary(wt_bl$AVAL))

# ---- Export ----
write_adam(advs, "advs")
saveRDS(advs, file.path(ADAM_DIR, "advs.rds"))
