# Name: 08_advs.R
# Description: Generate ADVS dataset for CDISCPILOT01
# Source SDTM: VS, ADSL
# Supports TLGs: T-14.3.3.1, T-14.3.3.2, T-14.3.4.1
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

# ---- Setup ----
library(admiral)
library(dplyr)
library(lubridate)
library(stringr)
library(tidyr)

# Source helper functions
source("/workspace/code/00_setup.R")

# ---- Read source data ----
cat("Reading source data...\n")
vs <- read_sdtm("VS")
adsl <- readRDS("/workspace/data/adsl.rds")

# ---- Prepare VS data ----
cat("Preparing VS data...\n")
vsprep <- vs %>%
  filter(!is.na(VSSTRESN)) %>%
  mutate(
    VSSEQ = as.numeric(VSSEQ),
    VSTESTCD = VSTESTCD,
    VSTEST = VSTEST,
    VSCAT = VSCAT,
    VSORRES = VSORRES,
    VSORRESU = VSORRESU,
    VSSTRESC = VSSTRESC,
    VSSTRESN = as.numeric(VSSTRESN),
    VSSTRESU = VSSTRESU,
    VSDTC = VSDTC,
    VISITNUM = VISITNUM,
    VISIT = VISIT,
    AVAL = VSSTRESN,
    BASE = NA_real_  # Will be filled later
  ) %>%
  select(
    USUBJID, VSSEQ, VSTESTCD, VSTEST, VSCAT,
    VSORRES, VSORRESU, VSSTRESC, VSSTRESN, VSSTRESU,
    VSDTC, VISITNUM, VISIT, AVAL, BASE
  )

# ---- Define analysis ranges for categorical analysis ----
cat("Defining analysis ranges...\n")
# Common thresholds for vital signs
vs_ranges <- tribble(
  ~VSTESTCD, ~A1LO, ~A1HI, ~CAT_DESC,
  "SYSBP", 90, 140, "Systolic Blood Pressure",
  "DIABP", 60, 90, "Diastolic Blood Pressure",
  "PULSE", 50, 100, "Pulse Rate",
  "WEIGHT", NA, NA, "Weight",
  "HEIGHT", NA, NA, "Height",
  "TEMP", 36.0, 37.5, "Temperature",
  "RESP", 12, 20, "Respiratory Rate"
)

# ---- Derive baseline values ----
cat("Deriving baseline values...\n")
base_vs <- vsprep %>%
  filter(VISITNUM == 3) %>%  # Baseline visit
  group_by(USUBJID, VSTESTCD) %>%
  arrange(VSDTC) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  select(USUBJID, VSTESTCD, BASE = AVAL)

# ---- Create ADVS structure ----
cat("Creating ADVS structure...\n")
advs <- vsprep %>%
  left_join(base_vs, by = c("USUBJID", "VSTESTCD")) %>%
  left_join(vs_ranges, by = "VSTESTCD") %>%
  mutate(
    CHG = ifelse(VISITNUM != 3, AVAL - BASE, NA_real_),
    ANRIND = case_when(
      !is.na(A1LO) & !is.na(A1HI) & AVAL < A1LO ~ "LOW",
      !is.na(A1LO) & !is.na(A1HI) & AVAL > A1HI ~ "HIGH",
      !is.na(A1LO) & !is.na(A1HI) & AVAL >= A1LO & AVAL <= A1HI ~ "NORMAL",
      TRUE ~ NA_character_
    )
  )

# ---- Add treatment variables ----
cat("Adding treatment variables...\n")
advs_final <- advs %>%
  left_join(
    adsl %>% select(USUBJID, TRT01P, TRT01PN, SAFFL),
    by = "USUBJID"
  ) %>%
  mutate(
    TRTP = TRT01P,
    TRTPN = TRT01PN
  ) %>%
  filter(SAFFL == "Y") %>%  # Keep only safety population
  select(-SAFFL)

# ---- Add labels ----
cat("Adding variable labels...\n")
attr(advs_final$USUBJID, "label") <- "Unique Subject Identifier"
attr(advs_final$VSSEQ, "label") <- "Sequence Number"
attr(advs_final$VSTESTCD, "label") <- "Vital Signs Test Short Name"
attr(advs_final$VSTEST, "label") <- "Vital Signs Test Name"
attr(advs_final$VSCAT, "label") <- "Category for Vital Signs"
attr(advs_final$VSORRES, "label") <- "Result or Finding in Original Units"
attr(advs_final$VSORRESU, "label") <- "Original Units"
attr(advs_final$VSSTRESC, "label") <- "Character Result/Finding in Std Format"
attr(advs_final$VSSTRESN, "label") <- "Numeric Result/Finding in Standard Units"
attr(advs_final$VSSTRESU, "label") <- "Standard Units"
attr(advs_final$VSDTC, "label") <- "Date/Time of Measurements"
attr(advs_final$VISITNUM, "label") <- "Visit Number"
attr(advs_final$VISIT, "label") <- "Visit Name"
attr(advs_final$AVAL, "label") <- "Analysis Value"
attr(advs_final$BASE, "label") <- "Baseline Value"
attr(advs_final$CHG, "label") <- "Change from Baseline"
attr(advs_final$A1LO, "label") <- "Analysis Range Low Value"
attr(advs_final$A1HI, "label") <- "Analysis Range High Value"
attr(advs_final$ANRIND, "label") <- "Analysis Reference Range Indicator"
attr(advs_final$TRTP, "label") <- "Planned Treatment"
attr(advs_final$TRTPN, "label") <- "Planned Treatment (N)"

# ---- Export ----
cat("Exporting ADVS dataset...\n")
output_dir <- "/workspace/data"
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# Export to Dataset-JSON
tryCatch({
  datasetjson::write_dataset_json(\1, file.path(output_dir, "\2"))
  cat("Exported to Dataset-JSON format.\\n")
}, error = function(e) {
  cat("Dataset-JSON export failed:", e$message, "\\n")
  cat("Saving as RDS only.\\n")
})
saveRDS(\1, file.path(output_dir, "\3"))
cat("Saved as RDS format.\\n")

cat("ADVS generation complete. Records:", nrow(advs_final), "\n")
cat("Vital signs tests:", n_distinct(advs_final$VSTESTCD), "\n")
cat("Output saved to:", file.path(output_dir, "advs.json"), "\n")