# Name: 08_adex.R
# Description: Generate ADEX (Exposure Analysis Dataset)
# Source SDTM: EX, ADSL
# Supports TLGs: T-17
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

source("/private/var/folders/k_/kns3xnh95lsc57yvx3rhxj100000gn/T/mediforce-local-workspace-hB8wZb/code/00_setup.R")

# ---- Read source data ----
ex   <- read_sdtm("ex")
adsl <- readRDS(file.path(ADAM_DIR, "adsl.rds"))

# ---- Join with ADSL ----
adsl_sub <- adsl %>%
  select(USUBJID, STUDYID, TRT01A, TRT01AN, SAFFL, ITTFL, COMPFL, TRTSDT, TRTEDT, TRTDUR,
         SITEID, AGE, SEX, RACE, ARMCD)

# ---- Process exposure records ----
adex_raw <- ex %>%
  left_join(adsl_sub, by = "USUBJID") %>%
  filter(SAFFL == "Y") %>%
  mutate(
    ASTDT  = as.Date(substr(EXSTDTC, 1, 10)),
    AENDT  = as.Date(substr(EXENDTC, 1, 10)),
    ASTDY  = EXSTDY,
    AENDY  = EXENDY,

    # Duration of this exposure period in days
    EXDUR  = as.integer(AENDT - ASTDT + 1),

    PARAMCD = "EXDOSE",
    PARAM   = "Dose (mg)",
    AVAL    = EXDOSE,
    DOMAIN  = "ADEX",
    STUDYID = "CDISCPILOT01"
  )

# ---- Compute cumulative and average daily dose per subject ----
adex_summary <- adex_raw %>%
  filter(EXTRT != "PLACEBO" | EXDOSE == 0) %>%  # all subjects
  group_by(USUBJID) %>%
  summarise(
    CUMEXDOS = sum(EXDOSE * pmax(EXDUR, 0, na.rm = TRUE), na.rm = TRUE),
    TOTEXDUR = sum(pmax(EXDUR, 0, na.rm = TRUE), na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    AVGDOSE = if_else(TOTEXDUR > 0, CUMEXDOS / TOTEXDUR, NA_real_)
  )

# ---- Build ADEX: one record per subject per exposure interval + summary parameters ----
# Interval-level records
adex_intervals <- adex_raw %>%
  select(
    STUDYID, USUBJID, DOMAIN, EXSEQ,
    PARAMCD, PARAM, AVAL,
    EXTRT, EXDOSU, EXDOSFRM, EXDOSFRQ, EXROUTE,
    ASTDT, ASTDY, AENDT, AENDY, EXDUR,
    VISITNUM, VISIT,
    TRT01A, TRT01AN, SAFFL, ITTFL, COMPFL,
    SITEID, AGE, SEX, RACE, ARMCD,
    TRTSDT, TRTEDT, TRTDUR
  )

# Summary-level records (average daily dose and cumulative dose)
adex_sumrec <- adsl_sub %>%
  filter(SAFFL == "Y") %>%
  left_join(adex_summary, by = "USUBJID") %>%
  mutate(STUDYID = "CDISCPILOT01", DOMAIN = "ADEX") %>%
  select(
    STUDYID, USUBJID, DOMAIN,
    CUMEXDOS, AVGDOSE, TOTEXDUR,
    TRT01A, TRT01AN, SAFFL, ITTFL, COMPFL,
    SITEID, AGE, SEX, RACE, ARMCD,
    TRTSDT, TRTEDT, TRTDUR
  )

# ---- Validate ----
cat("ADEX interval rows:", nrow(adex_intervals), "\n")
cat("ADEX summary rows:", nrow(adex_sumrec), "\n")
cat("Subjects:", n_distinct(adex_intervals$USUBJID), "\n")
cat("\nAverage daily dose by arm:\n")
print(
  adex_sumrec %>%
    group_by(TRT01A) %>%
    summarise(
      N = n(),
      MEAN_AVGDOSE = round(mean(AVGDOSE, na.rm=TRUE), 1),
      MEAN_TRTDUR  = round(mean(TOTEXDUR, na.rm=TRUE), 1),
      .groups = "drop"
    )
)

# ---- Export ----
write_adam(adex_sumrec, "adex")
saveRDS(adex_sumrec, file.path(ADAM_DIR, "adex.rds"))
saveRDS(adex_intervals, file.path(ADAM_DIR, "adex_intervals.rds"))
