# Name: 09_adcm.R
# Description: Generate ADCM (Concomitant Medications Analysis Dataset)
# Source SDTM: CM, ADSL
# Supports TLGs: T-29
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

source("/private/var/folders/k_/kns3xnh95lsc57yvx3rhxj100000gn/T/mediforce-local-workspace-hB8wZb/code/00_setup.R")

# ---- Read source data ----
cm   <- read_sdtm("cm")
adsl <- readRDS(file.path(ADAM_DIR, "adsl.rds"))

# ---- Join with ADSL ----
adsl_sub <- adsl %>%
  select(USUBJID, STUDYID, TRT01A, TRT01AN, SAFFL, ITTFL, TRTSDT, TRTEDT,
         SITEID, AGE, SEX, RACE, ARMCD)

adcm <- cm %>%
  left_join(adsl_sub, by = "USUBJID") %>%
  # All subjects with concomitant medications
  filter(!is.na(TRT01A)) %>%
  mutate(
    # Date handling - CM dates may be partial (year-only or year-month)
    # Pad partial dates to full ISO date for as.Date conversion
    CMSTDTC_PAD = case_when(
      nchar(CMSTDTC) == 4  ~ paste0(CMSTDTC, "-01-01"),
      nchar(CMSTDTC) == 7  ~ paste0(CMSTDTC, "-01"),
      TRUE ~ CMSTDTC
    ),
    CMENDTC_PAD = case_when(
      nchar(CMENDTC) == 4  ~ paste0(CMENDTC, "-12-31"),
      nchar(CMENDTC) == 7  ~ paste0(CMENDTC, "-28"),
      nchar(CMENDTC) == 0  ~ NA_character_,
      TRUE ~ CMENDTC
    ),
    ASTDT  = suppressWarnings(as.Date(substr(CMSTDTC_PAD, 1, 10))),
    AENDT  = suppressWarnings(as.Date(substr(CMENDTC_PAD, 1, 10))),
    ASTDY  = CMSTDY,
    AENDY  = CMENDY,

    # Treatment-emergent: started on or after treatment start
    TRTEMFL = if_else(
      !is.na(ASTDT) & !is.na(TRTSDT) & ASTDT >= TRTSDT,
      "Y", "N"
    ),

    # Concomitant (ongoing at treatment start): started before and ongoing at/after treatment start
    CMRFL = if_else(
      !is.na(ASTDT) & !is.na(TRTSDT) & ASTDT < TRTSDT &
        (is.na(AENDT) | AENDT >= TRTSDT),
      "Y", "N"
    ),

    # ATC classification (from CMCLAS)
    CMCLAS1 = CMCLAS,

    DOMAIN  = "ADCM",
    STUDYID = "CDISCPILOT01"
  ) %>%
  select(
    STUDYID, USUBJID, DOMAIN, CMSEQ,
    CMTRT, CMDECOD, CMINDC, CMCLAS1,
    CMDOSE, CMDOSU, CMDOSFRQ, CMROUTE,
    ASTDT, ASTDY, AENDT, AENDY,
    TRTEMFL, CMRFL,
    VISITNUM, VISIT,
    TRT01A, TRT01AN, SAFFL, ITTFL,
    SITEID, AGE, SEX, RACE, ARMCD,
    TRTSDT, TRTEDT
  ) %>%
  arrange(USUBJID, CMSEQ)

# ---- Validate ----
cat("ADCM rows:", nrow(adcm), "\n")
cat("Subjects:", n_distinct(adcm$USUBJID), "\n")
cat("Treatment-emergent CMs:", sum(adcm$TRTEMFL == "Y", na.rm = TRUE), "\n")
cat("CMs by arm:\n")
print(table(adcm$TRT01A))

# ---- Export ----
write_adam(adcm, "adcm")
saveRDS(adcm, file.path(ADAM_DIR, "adcm.rds"))
