# Name: 10_adtte.R
# Description: Generate ADTTE (Time-to-Event Analysis Dataset)
# Source SDTM: ADAE (derived), ADSL
# Supports TLGs: F-01 (Kaplan-Meier: Time to First Dermatological Event)
# Author: Generated by sdtm-to-adam skill
# Date: 2026-03-13

source("/private/var/folders/k_/kns3xnh95lsc57yvx3rhxj100000gn/T/mediforce-local-workspace-hB8wZb/code/00_setup.R")

# ---- Read source data ----
adae <- readRDS(file.path(ADAM_DIR, "adae.rds"))
adsl <- readRDS(file.path(ADAM_DIR, "adsl.rds"))

# ---- Parameter: Time to First Dermatological TEAE ----
# Event = first TEAE with SOC = "SKIN AND SUBCUTANEOUS TISSUE DISORDERS"
# Censoring = last known on-study date (treatment end)

derm_first <- adae %>%
  filter(TRTEMFL == "Y", DERM_FL == "Y") %>%
  group_by(USUBJID) %>%
  arrange(ASTDT) %>%
  slice(1) %>%
  ungroup() %>%
  select(USUBJID, EVNTDT = ASTDT, EVNTDY = ASTDY)

adsl_tte <- adsl %>%
  select(USUBJID, STUDYID, TRT01A, TRT01AN, SAFFL, ITTFL, TRTSDT, TRTEDT, TRTDUR,
         SITEID, AGE, AGEGR1, SEX, RACE, ARMCD) %>%
  filter(SAFFL == "Y")

adtte <- adsl_tte %>%
  left_join(derm_first, by = "USUBJID") %>%
  mutate(
    # Event indicator
    CNSR   = if_else(!is.na(EVNTDT), 0L, 1L),  # 0 = event, 1 = censored
    EVNTFL = if_else(CNSR == 0, "Y", "N"),

    # Time to event or censoring
    # Event date: EVNTDT
    # Censoring date: treatment end date (TRTEDT)
    CENSOR_DT = as.Date(TRTEDT),
    ADT = if_else(!is.na(EVNTDT), EVNTDT, CENSOR_DT),

    # Analysis day (days from treatment start + 1)
    AVAL = if_else(
      !is.na(ADT) & !is.na(TRTSDT),
      as.numeric(ADT - TRTSDT) + 1,
      NA_real_
    ),

    # Ensure AVAL >= 1
    AVAL = pmax(AVAL, 1, na.rm = TRUE),

    # Parameter
    PARAMCD = "TTDERM",
    PARAM   = "Time to First Dermatological TEAE (days)",
    PARAMN  = 1L,

    # Censoring reason
    CNSDTDSC = if_else(CNSR == 1, "LAST KNOWN ON-STUDY DATE", NA_character_),

    DOMAIN  = "ADTTE",
    STUDYID = "CDISCPILOT01"
  ) %>%
  select(
    STUDYID, USUBJID, DOMAIN,
    PARAMCD, PARAM, PARAMN,
    ADT, AVAL, CNSR, EVNTFL, CNSDTDSC,
    TRT01A, TRT01AN, SAFFL, ITTFL,
    SITEID, AGE, AGEGR1, SEX, RACE, ARMCD,
    TRTSDT, TRTEDT
  ) %>%
  arrange(USUBJID, PARAMCD)

# ---- Validate ----
cat("ADTTE rows:", nrow(adtte), "\n")
cat("Subjects:", n_distinct(adtte$USUBJID), "\n")
cat("\nEvents (CNSR=0):", sum(adtte$CNSR == 0), "\n")
cat("Censored (CNSR=1):", sum(adtte$CNSR == 1), "\n")
cat("\nEvents by arm:\n")
print(table(adtte$TRT01A[adtte$CNSR == 0]))
cat("\nAVAL summary:\n")
print(summary(adtte$AVAL))

# ---- Export ----
write_adam(adtte, "adtte")
saveRDS(adtte, file.path(ADAM_DIR, "adtte.rds"))
